// Code generated by cmd/vocabgen. DO NOT EDIT.

// Package dcterms is the DCMI Metadata Terms as OWL entities.
//
// Dublin Core's full term set: title, creator, subject, license,
// provenance and the rest of the descriptive metadata vocabulary that
// libraries, repositories and data portals have standardised on.
//
// Each term is a typed constant, so the compiler keeps a class out of a
// property's place. [Ontology] returns the axioms the vocabulary asserts
// about them, and [Vocabulary] the same terms with their labels attached.
//
// Source: https://www.dublincore.org/specifications/dublin-core/dcmi-terms/dublin_core_terms.ttl
// SHA-256: 13df401072dd7015bf9d75162f3e41c8138075304b7b9cc1aa1e9c16db976797
package dcterms

import (
	_ "embed"
	"sync"

	"gowl/owl"
)

// Prefix and Namespace are the vocabulary's customary prefix and the IRI it
// abbreviates.
const (
	Prefix            = "dcterms"
	Namespace owl.IRI = "http://purl.org/dc/terms/"
)

// Classes.
const (
	// VocabularyEncodingScheme is dcam:VocabularyEncodingScheme.
	VocabularyEncodingScheme owl.Class = "http://purl.org/dc/dcam/VocabularyEncodingScheme"

	// Collection is <http://purl.org/dc/dcmitype/Collection>.
	Collection owl.Class = "http://purl.org/dc/dcmitype/Collection"

	// Agent is dcterms:Agent.
	//
	// A resource that acts or has the power to act.
	Agent owl.Class = "http://purl.org/dc/terms/Agent"

	// AgentClass is dcterms:AgentClass, "Agent Class".
	//
	// A group of agents.
	AgentClass owl.Class = "http://purl.org/dc/terms/AgentClass"

	// BibliographicResource is dcterms:BibliographicResource, "Bibliographic
	// Resource".
	//
	// A book, article, or other documentary resource.
	BibliographicResource owl.Class = "http://purl.org/dc/terms/BibliographicResource"

	// FileFormat is dcterms:FileFormat, "File Format".
	//
	// A digital resource format.
	FileFormat owl.Class = "http://purl.org/dc/terms/FileFormat"

	// Frequency is dcterms:Frequency.
	//
	// A rate at which something recurs.
	Frequency owl.Class = "http://purl.org/dc/terms/Frequency"

	// Jurisdiction is dcterms:Jurisdiction.
	//
	// The extent or range of judicial, law enforcement, or other authority.
	Jurisdiction owl.Class = "http://purl.org/dc/terms/Jurisdiction"

	// LicenseDocument is dcterms:LicenseDocument, "License Document".
	//
	// A legal document giving official permission to do something with a
	// resource.
	LicenseDocument owl.Class = "http://purl.org/dc/terms/LicenseDocument"

	// LinguisticSystem is dcterms:LinguisticSystem, "Linguistic System".
	//
	// A system of signs, symbols, sounds, gestures, or rules used in
	// communication.
	LinguisticSystem owl.Class = "http://purl.org/dc/terms/LinguisticSystem"

	// Location is dcterms:Location.
	//
	// A spatial region or named place.
	Location owl.Class = "http://purl.org/dc/terms/Location"

	// LocationPeriodOrJurisdiction is dcterms:LocationPeriodOrJurisdiction,
	// "Location, Period, or Jurisdiction".
	//
	// A location, period of time, or jurisdiction.
	LocationPeriodOrJurisdiction owl.Class = "http://purl.org/dc/terms/LocationPeriodOrJurisdiction"

	// MediaType is dcterms:MediaType, "Media Type".
	//
	// A file format or physical medium.
	MediaType owl.Class = "http://purl.org/dc/terms/MediaType"

	// MediaTypeOrExtent is dcterms:MediaTypeOrExtent, "Media Type or Extent".
	//
	// A media type or extent.
	MediaTypeOrExtent owl.Class = "http://purl.org/dc/terms/MediaTypeOrExtent"

	// MethodOfAccrual is dcterms:MethodOfAccrual, "Method of Accrual".
	//
	// A method by which resources are added to a collection.
	MethodOfAccrual owl.Class = "http://purl.org/dc/terms/MethodOfAccrual"

	// MethodOfInstruction is dcterms:MethodOfInstruction, "Method of
	// Instruction".
	//
	// A process that is used to engender knowledge, attitudes, and skills.
	MethodOfInstruction owl.Class = "http://purl.org/dc/terms/MethodOfInstruction"

	// PeriodOfTime is dcterms:PeriodOfTime, "Period of Time".
	//
	// An interval of time that is named or defined by its start and end dates.
	PeriodOfTime owl.Class = "http://purl.org/dc/terms/PeriodOfTime"

	// PhysicalMedium is dcterms:PhysicalMedium, "Physical Medium".
	//
	// A physical material or carrier.
	PhysicalMedium owl.Class = "http://purl.org/dc/terms/PhysicalMedium"

	// PhysicalResource is dcterms:PhysicalResource, "Physical Resource".
	//
	// A material thing.
	PhysicalResource owl.Class = "http://purl.org/dc/terms/PhysicalResource"

	// Policy is dcterms:Policy.
	//
	// A plan or course of action by an authority, intended to influence and
	// determine decisions, actions, and other matters.
	Policy owl.Class = "http://purl.org/dc/terms/Policy"

	// ProvenanceStatement is dcterms:ProvenanceStatement, "Provenance
	// Statement".
	//
	// Any changes in ownership and custody of a resource since its creation
	// that are significant for its authenticity, integrity, and
	// interpretation.
	ProvenanceStatement owl.Class = "http://purl.org/dc/terms/ProvenanceStatement"

	// RightsStatement is dcterms:RightsStatement, "Rights Statement".
	//
	// A statement about the intellectual property rights (IPR) held in or over
	// a resource, a legal document giving official permission to do something
	// with a resource, or a statement about access rights.
	RightsStatement owl.Class = "http://purl.org/dc/terms/RightsStatement"

	// SizeOrDuration is dcterms:SizeOrDuration, "Size or Duration".
	//
	// A dimension or extent, or a time taken to play or execute.
	SizeOrDuration owl.Class = "http://purl.org/dc/terms/SizeOrDuration"

	// Standard is dcterms:Standard.
	//
	// A reference point against which other things can be evaluated or
	// compared.
	Standard owl.Class = "http://purl.org/dc/terms/Standard"
)

// Datatypes.
const (
	// Box is dcterms:Box, "DCMI Box".
	//
	// The set of regions in space defined by their geographic coordinates
	// according to the DCMI Box Encoding Scheme.
	Box owl.Datatype = "http://purl.org/dc/terms/Box"

	// ISO3166 is dcterms:ISO3166, "ISO 3166".
	//
	// The set of codes listed in ISO 3166-1 for the representation of names of
	// countries.
	ISO3166 owl.Datatype = "http://purl.org/dc/terms/ISO3166"

	// ISO6392 is dcterms:ISO639-2, "ISO 639-2".
	//
	// The three-letter alphabetic codes listed in ISO639-2 for the
	// representation of names of languages.
	ISO6392 owl.Datatype = "http://purl.org/dc/terms/ISO639-2"

	// ISO6393 is dcterms:ISO639-3, "ISO 639-3".
	//
	// The set of three-letter codes listed in ISO 639-3 for the representation
	// of names of languages.
	ISO6393 owl.Datatype = "http://purl.org/dc/terms/ISO639-3"

	// Period is dcterms:Period, "DCMI Period".
	//
	// The set of time intervals defined by their limits according to the DCMI
	// Period Encoding Scheme.
	Period owl.Datatype = "http://purl.org/dc/terms/Period"

	// Point is dcterms:Point, "DCMI Point".
	//
	// The set of points in space defined by their geographic coordinates
	// according to the DCMI Point Encoding Scheme.
	Point owl.Datatype = "http://purl.org/dc/terms/Point"

	// RFC1766 is dcterms:RFC1766, "RFC 1766".
	//
	// The set of tags, constructed according to RFC 1766, for the
	// identification of languages.
	RFC1766 owl.Datatype = "http://purl.org/dc/terms/RFC1766"

	// RFC3066 is dcterms:RFC3066, "RFC 3066".
	//
	// The set of tags constructed according to RFC 3066 for the identification
	// of languages.
	RFC3066 owl.Datatype = "http://purl.org/dc/terms/RFC3066"

	// RFC4646 is dcterms:RFC4646, "RFC 4646".
	//
	// The set of tags constructed according to RFC 4646 for the identification
	// of languages.
	RFC4646 owl.Datatype = "http://purl.org/dc/terms/RFC4646"

	// RFC5646 is dcterms:RFC5646, "RFC 5646".
	//
	// The set of tags constructed according to RFC 5646 for the identification
	// of languages.
	RFC5646 owl.Datatype = "http://purl.org/dc/terms/RFC5646"

	// URI is dcterms:URI.
	//
	// The set of identifiers constructed according to the generic syntax for
	// Uniform Resource Identifiers as specified by the Internet Engineering
	// Task Force.
	URI owl.Datatype = "http://purl.org/dc/terms/URI"

	// W3CDTF is dcterms:W3CDTF, "W3C-DTF".
	//
	// The set of dates and times constructed according to the W3C Date and
	// Time Formats Specification.
	W3CDTF owl.Datatype = "http://purl.org/dc/terms/W3CDTF"
)

// Object properties.
const (
	// Abstract is dcterms:abstract.
	//
	// A summary of the resource.
	Abstract owl.ObjectProperty = "http://purl.org/dc/terms/abstract"

	// AccessRights is dcterms:accessRights, "Access Rights".
	//
	// Information about who access the resource or an indication of its
	// security status.
	AccessRights owl.ObjectProperty = "http://purl.org/dc/terms/accessRights"

	// AccrualMethod is dcterms:accrualMethod, "Accrual Method".
	//
	// The method by which items are added to a collection.
	AccrualMethod owl.ObjectProperty = "http://purl.org/dc/terms/accrualMethod"

	// AccrualPeriodicity is dcterms:accrualPeriodicity, "Accrual Periodicity".
	//
	// The frequency with which items are added to a collection.
	AccrualPeriodicity owl.ObjectProperty = "http://purl.org/dc/terms/accrualPeriodicity"

	// AccrualPolicy is dcterms:accrualPolicy, "Accrual Policy".
	//
	// The policy governing the addition of items to a collection.
	AccrualPolicy owl.ObjectProperty = "http://purl.org/dc/terms/accrualPolicy"

	// Audience is dcterms:audience.
	//
	// A class of agents for whom the resource is intended or useful.
	Audience owl.ObjectProperty = "http://purl.org/dc/terms/audience"

	// ConformsTo is dcterms:conformsTo, "Conforms To".
	//
	// An established standard to which the described resource conforms.
	ConformsTo owl.ObjectProperty = "http://purl.org/dc/terms/conformsTo"

	// Contributor is dcterms:contributor.
	//
	// An entity responsible for making contributions to the resource.
	Contributor owl.ObjectProperty = "http://purl.org/dc/terms/contributor"

	// Coverage is dcterms:coverage.
	//
	// The spatial or temporal topic of the resource, spatial applicability of
	// the resource, or jurisdiction under which the resource is relevant.
	Coverage owl.ObjectProperty = "http://purl.org/dc/terms/coverage"

	// Creator is dcterms:creator.
	//
	// An entity responsible for making the resource.
	Creator owl.ObjectProperty = "http://purl.org/dc/terms/creator"

	// Description is dcterms:description.
	//
	// An account of the resource.
	Description owl.ObjectProperty = "http://purl.org/dc/terms/description"

	// EducationLevel is dcterms:educationLevel, "Audience Education Level".
	//
	// A class of agents, defined in terms of progression through an
	// educational or training context, for which the described resource is
	// intended.
	EducationLevel owl.ObjectProperty = "http://purl.org/dc/terms/educationLevel"

	// Extent is dcterms:extent.
	//
	// The size or duration of the resource.
	Extent owl.ObjectProperty = "http://purl.org/dc/terms/extent"

	// Format is dcterms:format.
	//
	// The file format, physical medium, or dimensions of the resource.
	Format owl.ObjectProperty = "http://purl.org/dc/terms/format"

	// HasFormat is dcterms:hasFormat, "Has Format".
	//
	// A related resource that is substantially the same as the pre-existing
	// described resource, but in another format.
	HasFormat owl.ObjectProperty = "http://purl.org/dc/terms/hasFormat"

	// HasPart is dcterms:hasPart, "Has Part".
	//
	// A related resource that is included either physically or logically in
	// the described resource.
	HasPart owl.ObjectProperty = "http://purl.org/dc/terms/hasPart"

	// HasVersion is dcterms:hasVersion, "Has Version".
	//
	// A related resource that is a version, edition, or adaptation of the
	// described resource.
	HasVersion owl.ObjectProperty = "http://purl.org/dc/terms/hasVersion"

	// InstructionalMethod is dcterms:instructionalMethod, "Instructional
	// Method".
	//
	// A process, used to engender knowledge, attitudes and skills, that the
	// described resource is designed to support.
	InstructionalMethod owl.ObjectProperty = "http://purl.org/dc/terms/instructionalMethod"

	// IsFormatOf is dcterms:isFormatOf, "Is Format Of".
	//
	// A pre-existing related resource that is substantially the same as the
	// described resource, but in another format.
	IsFormatOf owl.ObjectProperty = "http://purl.org/dc/terms/isFormatOf"

	// IsPartOf is dcterms:isPartOf, "Is Part Of".
	//
	// A related resource in which the described resource is physically or
	// logically included.
	IsPartOf owl.ObjectProperty = "http://purl.org/dc/terms/isPartOf"

	// IsReferencedBy is dcterms:isReferencedBy, "Is Referenced By".
	//
	// A related resource that references, cites, or otherwise points to the
	// described resource.
	IsReferencedBy owl.ObjectProperty = "http://purl.org/dc/terms/isReferencedBy"

	// IsReplacedBy is dcterms:isReplacedBy, "Is Replaced By".
	//
	// A related resource that supplants, displaces, or supersedes the
	// described resource.
	IsReplacedBy owl.ObjectProperty = "http://purl.org/dc/terms/isReplacedBy"

	// IsRequiredBy is dcterms:isRequiredBy, "Is Required By".
	//
	// A related resource that requires the described resource to support its
	// function, delivery, or coherence.
	IsRequiredBy owl.ObjectProperty = "http://purl.org/dc/terms/isRequiredBy"

	// IsVersionOf is dcterms:isVersionOf, "Is Version Of".
	//
	// A related resource of which the described resource is a version,
	// edition, or adaptation.
	IsVersionOf owl.ObjectProperty = "http://purl.org/dc/terms/isVersionOf"

	// Language is dcterms:language.
	//
	// A language of the resource.
	Language owl.ObjectProperty = "http://purl.org/dc/terms/language"

	// License is dcterms:license.
	//
	// A legal document giving official permission to do something with the
	// resource.
	License owl.ObjectProperty = "http://purl.org/dc/terms/license"

	// Mediator is dcterms:mediator.
	//
	// An entity that mediates access to the resource.
	Mediator owl.ObjectProperty = "http://purl.org/dc/terms/mediator"

	// Medium is dcterms:medium.
	//
	// The material or physical carrier of the resource.
	Medium owl.ObjectProperty = "http://purl.org/dc/terms/medium"

	// Provenance is dcterms:provenance.
	//
	// A statement of any changes in ownership and custody of the resource
	// since its creation that are significant for its authenticity, integrity,
	// and interpretation.
	Provenance owl.ObjectProperty = "http://purl.org/dc/terms/provenance"

	// Publisher is dcterms:publisher.
	//
	// An entity responsible for making the resource available.
	Publisher owl.ObjectProperty = "http://purl.org/dc/terms/publisher"

	// References is dcterms:references.
	//
	// A related resource that is referenced, cited, or otherwise pointed to by
	// the described resource.
	References owl.ObjectProperty = "http://purl.org/dc/terms/references"

	// Relation is dcterms:relation.
	//
	// A related resource.
	Relation owl.ObjectProperty = "http://purl.org/dc/terms/relation"

	// Replaces is dcterms:replaces.
	//
	// A related resource that is supplanted, displaced, or superseded by the
	// described resource.
	Replaces owl.ObjectProperty = "http://purl.org/dc/terms/replaces"

	// Requires is dcterms:requires.
	//
	// A related resource that is required by the described resource to support
	// its function, delivery, or coherence.
	Requires owl.ObjectProperty = "http://purl.org/dc/terms/requires"

	// Rights is dcterms:rights.
	//
	// Information about rights held in and over the resource.
	Rights owl.ObjectProperty = "http://purl.org/dc/terms/rights"

	// RightsHolder is dcterms:rightsHolder, "Rights Holder".
	//
	// A person or organization owning or managing rights over the resource.
	RightsHolder owl.ObjectProperty = "http://purl.org/dc/terms/rightsHolder"

	// Source is dcterms:source.
	//
	// A related resource from which the described resource is derived.
	Source owl.ObjectProperty = "http://purl.org/dc/terms/source"

	// Spatial is dcterms:spatial, "Spatial Coverage".
	//
	// Spatial characteristics of the resource.
	Spatial owl.ObjectProperty = "http://purl.org/dc/terms/spatial"

	// Subject is dcterms:subject.
	//
	// A topic of the resource.
	Subject owl.ObjectProperty = "http://purl.org/dc/terms/subject"

	// TableOfContents is dcterms:tableOfContents, "Table Of Contents".
	//
	// A list of subunits of the resource.
	TableOfContents owl.ObjectProperty = "http://purl.org/dc/terms/tableOfContents"

	// Temporal is dcterms:temporal, "Temporal Coverage".
	//
	// Temporal characteristics of the resource.
	Temporal owl.ObjectProperty = "http://purl.org/dc/terms/temporal"

	// Type is dcterms:type.
	//
	// The nature or genre of the resource.
	Type owl.ObjectProperty = "http://purl.org/dc/terms/type"
)

// Data properties.
const (
	// Alternative is dcterms:alternative, "Alternative Title".
	//
	// An alternative name for the resource.
	Alternative owl.DataProperty = "http://purl.org/dc/terms/alternative"

	// Available is dcterms:available, "Date Available".
	//
	// Date that the resource became or will become available.
	Available owl.DataProperty = "http://purl.org/dc/terms/available"

	// BibliographicCitation is dcterms:bibliographicCitation, "Bibliographic
	// Citation".
	//
	// A bibliographic reference for the resource.
	BibliographicCitation owl.DataProperty = "http://purl.org/dc/terms/bibliographicCitation"

	// Created is dcterms:created, "Date Created".
	//
	// Date of creation of the resource.
	Created owl.DataProperty = "http://purl.org/dc/terms/created"

	// Date is dcterms:date.
	//
	// A point or period of time associated with an event in the lifecycle of
	// the resource.
	Date owl.DataProperty = "http://purl.org/dc/terms/date"

	// DateAccepted is dcterms:dateAccepted, "Date Accepted".
	//
	// Date of acceptance of the resource.
	DateAccepted owl.DataProperty = "http://purl.org/dc/terms/dateAccepted"

	// DateCopyrighted is dcterms:dateCopyrighted, "Date Copyrighted".
	//
	// Date of copyright of the resource.
	DateCopyrighted owl.DataProperty = "http://purl.org/dc/terms/dateCopyrighted"

	// DateSubmitted is dcterms:dateSubmitted, "Date Submitted".
	//
	// Date of submission of the resource.
	DateSubmitted owl.DataProperty = "http://purl.org/dc/terms/dateSubmitted"

	// Identifier is dcterms:identifier.
	//
	// An unambiguous reference to the resource within a given context.
	Identifier owl.DataProperty = "http://purl.org/dc/terms/identifier"

	// Issued is dcterms:issued, "Date Issued".
	//
	// Date of formal issuance of the resource.
	Issued owl.DataProperty = "http://purl.org/dc/terms/issued"

	// Modified is dcterms:modified, "Date Modified".
	//
	// Date on which the resource was changed.
	Modified owl.DataProperty = "http://purl.org/dc/terms/modified"

	// Title is dcterms:title.
	//
	// A name given to the resource.
	Title owl.DataProperty = "http://purl.org/dc/terms/title"

	// Valid is dcterms:valid, "Date Valid".
	//
	// Date (often a range) of validity of a resource.
	Valid owl.DataProperty = "http://purl.org/dc/terms/valid"
)

// Annotation properties.
const (
	// DomainIncludes is dcam:domainIncludes.
	DomainIncludes owl.AnnotationProperty = "http://purl.org/dc/dcam/domainIncludes"

	// RangeIncludes is dcam:rangeIncludes.
	RangeIncludes owl.AnnotationProperty = "http://purl.org/dc/dcam/rangeIncludes"

	// DescriptionAnnotation is dcterms:description.
	//
	// An account of the resource.
	DescriptionAnnotation owl.AnnotationProperty = "http://purl.org/dc/terms/description"

	// IssuedAnnotation is dcterms:issued, "Date Issued".
	//
	// Date of formal issuance of the resource.
	IssuedAnnotation owl.AnnotationProperty = "http://purl.org/dc/terms/issued"

	// ModifiedAnnotation is dcterms:modified, "Date Modified".
	//
	// Date on which the resource was changed.
	ModifiedAnnotation owl.AnnotationProperty = "http://purl.org/dc/terms/modified"

	// PublisherAnnotation is dcterms:publisher.
	//
	// An entity responsible for making the resource available.
	PublisherAnnotation owl.AnnotationProperty = "http://purl.org/dc/terms/publisher"

	// TitleAnnotation is dcterms:title.
	//
	// A name given to the resource.
	TitleAnnotation owl.AnnotationProperty = "http://purl.org/dc/terms/title"
)

// Individuals.
const (
	// AgentIndividual is dcterms:Agent.
	//
	// A resource that acts or has the power to act.
	AgentIndividual owl.NamedIndividual = "http://purl.org/dc/terms/Agent"

	// DCMIType is dcterms:DCMIType, "DCMI Type Vocabulary".
	//
	// The set of classes specified by the DCMI Type Vocabulary, used to
	// categorize the nature or genre of the resource.
	DCMIType owl.NamedIndividual = "http://purl.org/dc/terms/DCMIType"

	// DDC is dcterms:DDC.
	//
	// The set of conceptual resources specified by the Dewey Decimal
	// Classification.
	DDC owl.NamedIndividual = "http://purl.org/dc/terms/DDC"

	// IMT is dcterms:IMT.
	//
	// The set of media types specified by the Internet Assigned Numbers
	// Authority.
	IMT owl.NamedIndividual = "http://purl.org/dc/terms/IMT"

	// LCC is dcterms:LCC.
	//
	// The set of conceptual resources specified by the Library of Congress
	// Classification.
	LCC owl.NamedIndividual = "http://purl.org/dc/terms/LCC"

	// LCSH is dcterms:LCSH.
	//
	// The set of labeled concepts specified by the Library of Congress Subject
	// Headings.
	LCSH owl.NamedIndividual = "http://purl.org/dc/terms/LCSH"

	// MESH is dcterms:MESH.
	//
	// The set of labeled concepts specified by the Medical Subject Headings.
	MESH owl.NamedIndividual = "http://purl.org/dc/terms/MESH"

	// NLM is dcterms:NLM.
	//
	// The set of conceptual resources specified by the National Library of
	// Medicine Classification.
	NLM owl.NamedIndividual = "http://purl.org/dc/terms/NLM"

	// TGN is dcterms:TGN.
	//
	// The set of places specified by the Getty Thesaurus of Geographic Names.
	TGN owl.NamedIndividual = "http://purl.org/dc/terms/TGN"

	// UDC is dcterms:UDC.
	//
	// The set of conceptual resources specified by the Universal Decimal
	// Classification.
	UDC owl.NamedIndividual = "http://purl.org/dc/terms/UDC"
)

//go:embed dcterms.ofn
var source string

// Ontology returns the vocabulary's axioms: its declarations, its class and
// property hierarchy, and the labels and definitions its authors wrote.
//
// Each call parses a fresh ontology, so the result is the caller's to add to
// or rewrite. Use [Vocabulary] instead to look terms up without copying.
func Ontology() *owl.Ontology {
	o, err := owl.ParseFunctionalString(source)
	if err != nil {
		panic("dcterms: generated ontology does not parse: " + err.Error())
	}
	return o
}

// Vocabulary returns the terms with their labels and definitions, as the
// closed set an untrusted axiom can be validated against. It is built once and
// is safe to share.
func Vocabulary() *owl.Vocabulary { return vocabulary() }

var vocabulary = sync.OnceValue(func() *owl.Vocabulary {
	return owl.NewVocabulary(Ontology())
})
