// Code generated by cmd/vocabgen. DO NOT EDIT.

// Package time is the OWL-Time ontology as OWL entities.
//
// OWL-Time: instants, intervals, the thirteen Allen interval relations,
// and durations in both clock and calendar terms.
//
// Each term is a typed constant, so the compiler keeps a class out of a
// property's place. [Ontology] returns the axioms the vocabulary asserts
// about them, and [Vocabulary] the same terms with their labels attached.
//
// Source: https://www.w3.org/2006/time
// SHA-256: 251bd6970b0d7a5efa97ff681afe81a297df85deab3d860fa4f8eeba72d8f16c
package time

import (
	_ "embed"
	"sync"

	"gowl/owl"
)

// Prefix and Namespace are the vocabulary's customary prefix and the IRI it
// abbreviates.
const (
	Prefix            = "time"
	Namespace owl.IRI = "http://www.w3.org/2006/time#"
)

// Classes.
const (
	// DateTimeDescription is time:DateTimeDescription, "Date-Time
	// description".
	//
	// Descripción de fecha y tiempo estructurada con valores separados para
	// los diferentes elementos de un sistema calendario-reloj. El sistema de
	// referencia temporal está fijado al calendario gregoriano, y el rango de
	// las propiedades año, mes, día restringidas a los correspondientes
	// tipos del XML Schema xsd:gYear, xsd:gMonth y xsd:gDay respectivamente.
	DateTimeDescription owl.Class = "http://www.w3.org/2006/time#DateTimeDescription"

	// DateTimeInterval is time:DateTimeInterval, "Date-time interval".
	//
	// 'intervalo de fecha-hora' es una subclase de 'intervalo propio',
	// definida utilizando el multi-elemento 'descripción de fecha-hora'.
	DateTimeInterval owl.Class = "http://www.w3.org/2006/time#DateTimeInterval"

	// DayOfWeek is time:DayOfWeek, "Day of week".
	//
	// El día de la semana
	DayOfWeek owl.Class = "http://www.w3.org/2006/time#DayOfWeek"

	// Duration is time:Duration, "Time duration".
	//
	// Duración de una extensión temporal expresada como un número escalado
	// por una unidad temporal.
	Duration owl.Class = "http://www.w3.org/2006/time#Duration"

	// DurationDescription is time:DurationDescription, "Duration description".
	//
	// Descripción de extensión temporal estructurada con valores separados
	// para los distintos elementos de un sistema de horario-calendario. El
	// sistema de referencia temporal se fija al calendario gregoriano, y el
	// intervalo de cada una de las propiedades numéricas se restringe a
	// xsd:decimal.
	DurationDescription owl.Class = "http://www.w3.org/2006/time#DurationDescription"

	// GeneralDateTimeDescription is time:GeneralDateTimeDescription,
	// "Generalized date-time description".
	//
	// Descripción de fecha y hora estructurada con valores separados para los
	// distintos elementos de un sistema calendario-reloj.
	GeneralDateTimeDescription owl.Class = "http://www.w3.org/2006/time#GeneralDateTimeDescription"

	// GeneralDurationDescription is time:GeneralDurationDescription,
	// "Generalized duration description".
	//
	// Descripción de extensión temporal estructurada con valores separados
	// para los distintos elementos de un sistema de horario-calendario.
	GeneralDurationDescription owl.Class = "http://www.w3.org/2006/time#GeneralDurationDescription"

	// Instant is time:Instant, "Time instant".
	//
	// A temporal entity with zero extent or duration
	Instant owl.Class = "http://www.w3.org/2006/time#Instant"

	// Interval is time:Interval, "Time interval".
	//
	// A temporal entity with an extent or duration
	Interval owl.Class = "http://www.w3.org/2006/time#Interval"

	// January is time:January.
	January owl.Class = "http://www.w3.org/2006/time#January"

	// MonthOfYear is time:MonthOfYear, "Month of year".
	//
	// El mes del año.
	MonthOfYear owl.Class = "http://www.w3.org/2006/time#MonthOfYear"

	// ProperInterval is time:ProperInterval, "Proper interval".
	//
	// A temporal entity with non-zero extent or duration, i.e. for which the
	// value of the beginning and end are different
	ProperInterval owl.Class = "http://www.w3.org/2006/time#ProperInterval"

	// TRS is time:TRS, "Temporal Reference System".
	//
	// A temporal reference system, such as a temporal coordinate system (with
	// an origin, direction, and scale), a calendar-clock combination, or a
	// (possibly hierarchical) ordinal system. This is a stub class,
	// representing the set of all temporal reference systems.
	TRS owl.Class = "http://www.w3.org/2006/time#TRS"

	// TemporalDuration is time:TemporalDuration, "Temporal duration".
	//
	// Extensión de tiempo; duración de un intervalo de tiempo independiente
	// de su posición de inicio particular.
	TemporalDuration owl.Class = "http://www.w3.org/2006/time#TemporalDuration"

	// TemporalEntity is time:TemporalEntity, "Temporal entity".
	//
	// A temporal interval or instant.
	TemporalEntity owl.Class = "http://www.w3.org/2006/time#TemporalEntity"

	// TemporalPosition is time:TemporalPosition, "Temporal position".
	//
	// A position on a time-line
	TemporalPosition owl.Class = "http://www.w3.org/2006/time#TemporalPosition"

	// TemporalUnit is time:TemporalUnit, "Temporal unit".
	//
	// A standard duration, which provides a scale factor for a time extent, or
	// the granularity or precision for a time position.
	TemporalUnit owl.Class = "http://www.w3.org/2006/time#TemporalUnit"

	// TimePosition is time:TimePosition, "Time position".
	//
	// A temporal position described using either a (nominal) value from an
	// ordinal reference system, or a (numeric) value in a temporal coordinate
	// system.
	TimePosition owl.Class = "http://www.w3.org/2006/time#TimePosition"

	// TimeZone is time:TimeZone, "Time Zone".
	//
	// A Time Zone specifies the amount by which the local time is offset from
	// UTC. A time zone is usually denoted geographically (e.g. Australian
	// Eastern Daylight Time), with a constant value in a given region. The
	// region where it applies and the offset from UTC are specified by a
	// locally recognised governing authority.
	TimeZone owl.Class = "http://www.w3.org/2006/time#TimeZone"

	// Year is time:Year.
	//
	// Year duration
	Year owl.Class = "http://www.w3.org/2006/time#Year"
)

// Datatypes.
const (
	// GeneralDay is time:generalDay, "Día generalizado".
	//
	// Day of month - formulated as a text string with a pattern constraint to
	// reproduce the same lexical form as gDay, except that values up to 99 are
	// permitted, in order to support calendars with more than 31 days in a
	// month. Note that the value-space is not defined, so a generic OWL2
	// processor cannot compute ordering relationships of values of this type.
	GeneralDay owl.Datatype = "http://www.w3.org/2006/time#generalDay"

	// GeneralMonth is time:generalMonth, "Generalized month".
	//
	// Mes del año - formulado como una cadena de texto con una restricción
	// patrón para reproducir la misma forma léxica que gMonth, excepto que
	// se permiten valores hasta el 20, con el propósito de proporcionar
	// soporte a calendarios con años con más de 12 meses. Nótese que el
	// espacio de valores no está definido, por tanto, un procesador genérico
	// de OWL2 no puede computar relaciones de orden de valores de este tipo.
	GeneralMonth owl.Datatype = "http://www.w3.org/2006/time#generalMonth"

	// GeneralYear is time:generalYear, "Año generalizado".
	//
	// Número de año - formulado como una cadena de texto con una
	// restricción patrón para reproducir la misma forma léxica que gYear,
	// aunque no está restringido a valores del calendario gregoriano. Nótese
	// que el espacio de valores no está definido, por tanto, un procesador
	// genérico de OWL2 no puede computar relaciones de orden de valores de
	// este tipo.
	GeneralYear owl.Datatype = "http://www.w3.org/2006/time#generalYear"
)

// Object properties.
const (
	// After is time:after.
	//
	// Asume una dirección en el tiempo. Si una entidad temporal T1 está
	// después de otra entidad temporal T2, entonces el principio de T1 está
	// después del final de T2.
	After owl.ObjectProperty = "http://www.w3.org/2006/time#after"

	// Before is time:before, "antes".
	//
	// Asume una dirección en el tiempo. Si una entidad temporal T1 está
	// antes que otra entidad temporal T2, entonces el final de T1 está antes
	// que el principio de T2. Así, "antes" se puede considerar básica para
	// instantes y derivada para intervalos.
	Before owl.ObjectProperty = "http://www.w3.org/2006/time#before"

	// DayOfWeekProperty is time:dayOfWeek, "day of week".
	//
	// El día de la semana, cuyo valor es un miembro de la clase 'día de la
	// semana'.
	DayOfWeekProperty owl.ObjectProperty = "http://www.w3.org/2006/time#dayOfWeek"

	// HasBeginning is time:hasBeginning, "has beginning".
	//
	// Beginning of a temporal entity
	HasBeginning owl.ObjectProperty = "http://www.w3.org/2006/time#hasBeginning"

	// HasDateTimeDescription is time:hasDateTimeDescription, "has Date-Time
	// description".
	//
	// Valor de intervalo de fecha-hora expresado como un valor estructurado.
	// El principio y el final del intervalo coincide con los límites del
	// elemento más corto en la descripción.
	HasDateTimeDescription owl.ObjectProperty = "http://www.w3.org/2006/time#hasDateTimeDescription"

	// HasDuration is time:hasDuration, "has duration".
	//
	// Duración de una entidad temporal, expresada como un valor escalado o un
	// valor nominal.
	HasDuration owl.ObjectProperty = "http://www.w3.org/2006/time#hasDuration"

	// HasDurationDescription is time:hasDurationDescription, "has duration
	// description".
	//
	// Duración de una entidad temporal, expresada utilizando una descripción
	// estructurada.
	HasDurationDescription owl.ObjectProperty = "http://www.w3.org/2006/time#hasDurationDescription"

	// HasEnd is time:hasEnd, "has end".
	//
	// End of a temporal entity.
	HasEnd owl.ObjectProperty = "http://www.w3.org/2006/time#hasEnd"

	// HasTRS is time:hasTRS, "Temporal reference system used".
	//
	// El sistema de referencia temporal utilizado por una posición temporal o
	// descripción de extensión.
	HasTRS owl.ObjectProperty = "http://www.w3.org/2006/time#hasTRS"

	// HasTemporalDuration is time:hasTemporalDuration, "has temporal
	// duration".
	//
	// Duración de una entidad temporal.
	HasTemporalDuration owl.ObjectProperty = "http://www.w3.org/2006/time#hasTemporalDuration"

	// HasTime is time:hasTime, "has time".
	//
	// Proporciona soporte a la asociación de una entidad temporal (instante o
	// intervalo) a cualquier cosa.
	HasTime owl.ObjectProperty = "http://www.w3.org/2006/time#hasTime"

	// InDateTime is time:inDateTime, "en descripción de fecha-hora".
	//
	// Posición de un instante, expresada utilizando una descripción
	// estructurada.
	InDateTime owl.ObjectProperty = "http://www.w3.org/2006/time#inDateTime"

	// InTemporalPosition is time:inTemporalPosition, "Temporal position".
	//
	// Posición de un instante de tiempo.
	InTemporalPosition owl.ObjectProperty = "http://www.w3.org/2006/time#inTemporalPosition"

	// InTimePosition is time:inTimePosition, "Time position".
	//
	// Posición de un instante, expresada como una coordenada temporal o un
	// valor nominal.
	InTimePosition owl.ObjectProperty = "http://www.w3.org/2006/time#inTimePosition"

	// Inside is time:inside, "has time instant inside".
	//
	// An instant that falls inside the interval. It is not intended to include
	// beginnings and ends of intervals.
	Inside owl.ObjectProperty = "http://www.w3.org/2006/time#inside"

	// IntervalAfter is time:intervalAfter, "interval after".
	//
	// If a proper interval T1 is intervalAfter another proper interval T2,
	// then the beginning of T1 is after the end of T2.
	IntervalAfter owl.ObjectProperty = "http://www.w3.org/2006/time#intervalAfter"

	// IntervalBefore is time:intervalBefore, "interval before".
	//
	// If a proper interval T1 is intervalBefore another proper interval T2,
	// then the end of T1 is before the beginning of T2.
	IntervalBefore owl.ObjectProperty = "http://www.w3.org/2006/time#intervalBefore"

	// IntervalContains is time:intervalContains, "interval contains".
	//
	// If a proper interval T1 is intervalContains another proper interval T2,
	// then the beginning of T1 is before the beginning of T2, and the end of
	// T1 is after the end of T2.
	IntervalContains owl.ObjectProperty = "http://www.w3.org/2006/time#intervalContains"

	// IntervalDisjoint is time:intervalDisjoint, "interval disjoint".
	//
	// If a proper interval T1 is intervalDisjoint another proper interval T2,
	// then the beginning of T1 is after the end of T2, or the end of T1 is
	// before the beginning of T2, i.e. the intervals do not overlap in any
	// way, but their ordering relationship is not known.
	IntervalDisjoint owl.ObjectProperty = "http://www.w3.org/2006/time#intervalDisjoint"

	// IntervalDuring is time:intervalDuring, "interval during".
	//
	// If a proper interval T1 is intervalDuring another proper interval T2,
	// then the beginning of T1 is after the beginning of T2, and the end of T1
	// is before the end of T2.
	IntervalDuring owl.ObjectProperty = "http://www.w3.org/2006/time#intervalDuring"

	// IntervalEquals is time:intervalEquals, "interval equals".
	//
	// If a proper interval T1 is intervalEquals another proper interval T2,
	// then the beginning of T1 is coincident with the beginning of T2, and the
	// end of T1 is coincident with the end of T2.
	IntervalEquals owl.ObjectProperty = "http://www.w3.org/2006/time#intervalEquals"

	// IntervalFinishedBy is time:intervalFinishedBy, "interval finished by".
	//
	// If a proper interval T1 is intervalFinishedBy another proper interval
	// T2, then the beginning of T1 is before the beginning of T2, and the end
	// of T1 is coincident with the end of T2.
	IntervalFinishedBy owl.ObjectProperty = "http://www.w3.org/2006/time#intervalFinishedBy"

	// IntervalFinishes is time:intervalFinishes, "interval finishes".
	//
	// If a proper interval T1 is intervalFinishes another proper interval T2,
	// then the beginning of T1 is after the beginning of T2, and the end of T1
	// is coincident with the end of T2.
	IntervalFinishes owl.ObjectProperty = "http://www.w3.org/2006/time#intervalFinishes"

	// IntervalIn is time:intervalIn, "interval in".
	//
	// If a proper interval T1 is intervalIn another proper interval T2, then
	// the beginning of T1 is after the beginning of T2 or is coincident with
	// the beginning of T2, and the end of T1 is before the end of T2, or is
	// coincident with the end of T2, except that end of T1 may not be
	// coincident with the end of T2 if the beginning of T1 is coincident with
	// the beginning of T2.
	IntervalIn owl.ObjectProperty = "http://www.w3.org/2006/time#intervalIn"

	// IntervalMeets is time:intervalMeets, "interval meets".
	//
	// If a proper interval T1 is intervalMeets another proper interval T2,
	// then the end of T1 is coincident with the beginning of T2.
	IntervalMeets owl.ObjectProperty = "http://www.w3.org/2006/time#intervalMeets"

	// IntervalMetBy is time:intervalMetBy, "interval met by".
	//
	// If a proper interval T1 is intervalMetBy another proper interval T2,
	// then the beginning of T1 is coincident with the end of T2.
	IntervalMetBy owl.ObjectProperty = "http://www.w3.org/2006/time#intervalMetBy"

	// IntervalOverlappedBy is time:intervalOverlappedBy, "interval overlapped
	// by".
	//
	// If a proper interval T1 is intervalOverlappedBy another proper interval
	// T2, then the beginning of T1 is after the beginning of T2, the beginning
	// of T1 is before the end of T2, and the end of T1 is after the end of T2.
	IntervalOverlappedBy owl.ObjectProperty = "http://www.w3.org/2006/time#intervalOverlappedBy"

	// IntervalOverlaps is time:intervalOverlaps, "interval overlaps".
	//
	// Asume una dirección en el tiempo. Si una entidad temporal T1 está
	// después de otra entidad temporal T2, entonces el principio de T1 está
	// después del final de T2.
	IntervalOverlaps owl.ObjectProperty = "http://www.w3.org/2006/time#intervalOverlaps"

	// IntervalStartedBy is time:intervalStartedBy, "interval started by".
	//
	// If a proper interval T1 is intervalStarted another proper interval T2,
	// then the beginning of T1 is coincident with the beginning of T2, and the
	// end of T1 is after the end of T2.
	IntervalStartedBy owl.ObjectProperty = "http://www.w3.org/2006/time#intervalStartedBy"

	// IntervalStarts is time:intervalStarts, "interval starts".
	//
	// If a proper interval T1 is intervalStarts another proper interval T2,
	// then the beginning of T1 is coincident with the beginning of T2, and the
	// end of T1 is before the end of T2.
	IntervalStarts owl.ObjectProperty = "http://www.w3.org/2006/time#intervalStarts"

	// MonthOfYearProperty is time:monthOfYear, "mes del año".
	//
	// El mes del año, cuyo valor es un miembro de la clase 'mes del año'.
	MonthOfYearProperty owl.ObjectProperty = "http://www.w3.org/2006/time#monthOfYear"

	// TimeZoneProperty is time:timeZone, "en huso horario".
	//
	// The time zone for clock elements in the temporal position
	TimeZoneProperty owl.ObjectProperty = "http://www.w3.org/2006/time#timeZone"

	// UnitType is time:unitType, "temporal unit type".
	//
	// La unidad de tiempo que proporciona la precisión de un valor fecha-hora
	// o la escala de una extensión temporal.
	UnitType owl.ObjectProperty = "http://www.w3.org/2006/time#unitType"
)

// Data properties.
const (
	// Day is time:day.
	//
	// Day position in a calendar-clock system. The range of this property is
	// not specified, so can be replaced by any specific representation of a
	// calendar day from any calendar.
	Day owl.DataProperty = "http://www.w3.org/2006/time#day"

	// DayOfYear is time:dayOfYear, "day of year".
	//
	// El número de día en el año.
	DayOfYear owl.DataProperty = "http://www.w3.org/2006/time#dayOfYear"

	// Days is time:days, "days duration".
	//
	// Longitud de, o elemento de la longitud de, una extensión temporal
	// expresada en días.
	Days owl.DataProperty = "http://www.w3.org/2006/time#days"

	// HasXSDDuration is time:hasXSDDuration, "has XSD duration".
	//
	// Extensión de una entidad temporal, expresada utilizando xsd:duration.
	HasXSDDuration owl.DataProperty = "http://www.w3.org/2006/time#hasXSDDuration"

	// Hour is time:hour, "hora".
	//
	// Hour position in a calendar-clock system.
	Hour owl.DataProperty = "http://www.w3.org/2006/time#hour"

	// Hours is time:hours, "duración en horas".
	//
	// Longitud de, o elemento de la longitud de, una extensión temporal
	// expresada en horas.
	Hours owl.DataProperty = "http://www.w3.org/2006/time#hours"

	// InXSDDate is time:inXSDDate, "en fecha XSD".
	//
	// Posición de un instante, expresado utilizando xsd:date.
	InXSDDate owl.DataProperty = "http://www.w3.org/2006/time#inXSDDate"

	// InXSDDateTime is time:inXSDDateTime, "en fecha-tiempo XSD".
	//
	// Posición de un instante, expresado utilizando xsd:dateTime.
	InXSDDateTime owl.DataProperty = "http://www.w3.org/2006/time#inXSDDateTime"

	// InXSDDateTimeStamp is time:inXSDDateTimeStamp, "en fecha-sello de tiempo
	// XSD".
	//
	// Posición de un instante, expresado utilizando xsd:dateTimeStamp.
	InXSDDateTimeStamp owl.DataProperty = "http://www.w3.org/2006/time#inXSDDateTimeStamp"

	// InXSDgYear is time:inXSDgYear, "en año gregoriano XSD".
	//
	// Posición de un instante, expresado utilizando xsd:gYear.
	InXSDgYear owl.DataProperty = "http://www.w3.org/2006/time#inXSDgYear"

	// InXSDgYearMonth is time:inXSDgYearMonth, "en año-mes gregoriano XSD".
	//
	// Posición de un instante, expresado utilizando xsd:gYearMonth.
	InXSDgYearMonth owl.DataProperty = "http://www.w3.org/2006/time#inXSDgYearMonth"

	// Minute is time:minute.
	//
	// Minute position in a calendar-clock system.
	Minute owl.DataProperty = "http://www.w3.org/2006/time#minute"

	// Minutes is time:minutes.
	//
	// Longitud de, o elemento de la longitud de, una extensión temporal
	// expresada en minutos.
	Minutes owl.DataProperty = "http://www.w3.org/2006/time#minutes"

	// Month is time:month, "mes".
	//
	// Month position in a calendar-clock system. The range of this property is
	// not specified, so can be replaced by any specific representation of a
	// calendar month from any calendar.
	Month owl.DataProperty = "http://www.w3.org/2006/time#month"

	// Months is time:months, "duración en meses".
	//
	// Longitud de, o elemento de la longitud de, una extensión temporal
	// expresada en meses.
	Months owl.DataProperty = "http://www.w3.org/2006/time#months"

	// NominalPosition is time:nominalPosition, "Name of temporal position".
	//
	// El valor (nominal) que indica posición temporal en un sistema de
	// referencia ordinal.
	NominalPosition owl.DataProperty = "http://www.w3.org/2006/time#nominalPosition"

	// NumericDuration is time:numericDuration, "Numeric value of temporal
	// duration".
	//
	// Valor de una extensión temporal expresada como un número decimal
	// escalado por una unidad de tiempo.
	NumericDuration owl.DataProperty = "http://www.w3.org/2006/time#numericDuration"

	// NumericPosition is time:numericPosition, "Numeric value of temporal
	// position".
	//
	// El valor (numérico) que indica posición temporal en un sistema de
	// referencia ordinal.
	NumericPosition owl.DataProperty = "http://www.w3.org/2006/time#numericPosition"

	// Second is time:second.
	//
	// Posición de segundo en un sistema calendario-reloj.
	Second owl.DataProperty = "http://www.w3.org/2006/time#second"

	// Seconds is time:seconds, "duración en segundos".
	//
	// Longitud de, o elemento de la longitud de, una extensión temporal
	// expresada en segundos.
	Seconds owl.DataProperty = "http://www.w3.org/2006/time#seconds"

	// Week is time:week, "semana".
	//
	// Número de semana en el año.
	Week owl.DataProperty = "http://www.w3.org/2006/time#week"

	// Weeks is time:weeks, "duración en semanas".
	//
	// Longitud de, o elemento de la longitud de, una extensión temporal
	// expresada en semanas.
	Weeks owl.DataProperty = "http://www.w3.org/2006/time#weeks"

	// XsdDateTime is time:xsdDateTime, "has XSD date-time".
	//
	// Valor de 'intervalo de fecha-hora' expresado como un valor compacto.
	XsdDateTime owl.DataProperty = "http://www.w3.org/2006/time#xsdDateTime"

	// YearDataProperty is time:year.
	//
	// Posición de año en un sistema calendario-reloj. l rango de esta
	// propiedad no está especificado, por tanto, se puede reemplazar por
	// cualquier representación específica de un año de calendario de un
	// calendario cualquiera.
	YearDataProperty owl.DataProperty = "http://www.w3.org/2006/time#year"

	// Years is time:years, "duración en años".
	//
	// Longitud de, o elemento de la longitud de, una extensión temporal
	// expresada en años.
	Years owl.DataProperty = "http://www.w3.org/2006/time#years"
)

// Annotation properties.
const (
	// DaysAnnotation is time:days, "days duration".
	//
	// Longitud de, o elemento de la longitud de, una extensión temporal
	// expresada en días.
	DaysAnnotation owl.AnnotationProperty = "http://www.w3.org/2006/time#days"

	// HoursAnnotation is time:hours, "duración en horas".
	//
	// Longitud de, o elemento de la longitud de, una extensión temporal
	// expresada en horas.
	HoursAnnotation owl.AnnotationProperty = "http://www.w3.org/2006/time#hours"

	// MinutesAnnotation is time:minutes.
	//
	// Longitud de, o elemento de la longitud de, una extensión temporal
	// expresada en minutos.
	MinutesAnnotation owl.AnnotationProperty = "http://www.w3.org/2006/time#minutes"

	// MonthsAnnotation is time:months, "duración en meses".
	//
	// Longitud de, o elemento de la longitud de, una extensión temporal
	// expresada en meses.
	MonthsAnnotation owl.AnnotationProperty = "http://www.w3.org/2006/time#months"

	// SecondsAnnotation is time:seconds, "duración en segundos".
	//
	// Longitud de, o elemento de la longitud de, una extensión temporal
	// expresada en segundos.
	SecondsAnnotation owl.AnnotationProperty = "http://www.w3.org/2006/time#seconds"

	// WeeksAnnotation is time:weeks, "duración en semanas".
	//
	// Longitud de, o elemento de la longitud de, una extensión temporal
	// expresada en semanas.
	WeeksAnnotation owl.AnnotationProperty = "http://www.w3.org/2006/time#weeks"

	// YearsAnnotation is time:years, "duración en años".
	//
	// Longitud de, o elemento de la longitud de, una extensión temporal
	// expresada en años.
	YearsAnnotation owl.AnnotationProperty = "http://www.w3.org/2006/time#years"
)

// Individuals.
const (
	// Friday is time:Friday.
	Friday owl.NamedIndividual = "http://www.w3.org/2006/time#Friday"

	// JanuaryIndividual is time:January.
	JanuaryIndividual owl.NamedIndividual = "http://www.w3.org/2006/time#January"

	// Monday is time:Monday.
	Monday owl.NamedIndividual = "http://www.w3.org/2006/time#Monday"

	// Saturday is time:Saturday.
	Saturday owl.NamedIndividual = "http://www.w3.org/2006/time#Saturday"

	// Sunday is time:Sunday.
	Sunday owl.NamedIndividual = "http://www.w3.org/2006/time#Sunday"

	// Thursday is time:Thursday.
	Thursday owl.NamedIndividual = "http://www.w3.org/2006/time#Thursday"

	// Tuesday is time:Tuesday.
	Tuesday owl.NamedIndividual = "http://www.w3.org/2006/time#Tuesday"

	// Wednesday is time:Wednesday.
	Wednesday owl.NamedIndividual = "http://www.w3.org/2006/time#Wednesday"

	// YearIndividual is time:Year.
	//
	// Year duration
	YearIndividual owl.NamedIndividual = "http://www.w3.org/2006/time#Year"

	// InXSDDateTimeIndividual is time:inXSDDateTime, "en fecha-tiempo XSD".
	//
	// Posición de un instante, expresado utilizando xsd:dateTime.
	InXSDDateTimeIndividual owl.NamedIndividual = "http://www.w3.org/2006/time#inXSDDateTime"

	// UnitDay is time:unitDay, "Day (unit of temporal duration)".
	UnitDay owl.NamedIndividual = "http://www.w3.org/2006/time#unitDay"

	// UnitHour is time:unitHour, "Hour (unit of temporal duration)".
	UnitHour owl.NamedIndividual = "http://www.w3.org/2006/time#unitHour"

	// UnitMinute is time:unitMinute, "Minute (unit of temporal duration)".
	UnitMinute owl.NamedIndividual = "http://www.w3.org/2006/time#unitMinute"

	// UnitMonth is time:unitMonth, "Month (unit of temporal duration)".
	UnitMonth owl.NamedIndividual = "http://www.w3.org/2006/time#unitMonth"

	// UnitSecond is time:unitSecond, "Second (unit of temporal duration)".
	UnitSecond owl.NamedIndividual = "http://www.w3.org/2006/time#unitSecond"

	// UnitWeek is time:unitWeek, "Week (unit of temporal duration)".
	UnitWeek owl.NamedIndividual = "http://www.w3.org/2006/time#unitWeek"

	// UnitYear is time:unitYear, "Year (unit of temporal duration)".
	UnitYear owl.NamedIndividual = "http://www.w3.org/2006/time#unitYear"

	// XsdDateTimeIndividual is time:xsdDateTime, "has XSD date-time".
	//
	// Valor de 'intervalo de fecha-hora' expresado como un valor compacto.
	XsdDateTimeIndividual owl.NamedIndividual = "http://www.w3.org/2006/time#xsdDateTime"
)

//go:embed time.ofn
var source string

// Ontology returns the vocabulary's axioms: its declarations, its class and
// property hierarchy, and the labels and definitions its authors wrote.
//
// Each call parses a fresh ontology, so the result is the caller's to add to
// or rewrite. Use [Vocabulary] instead to look terms up without copying.
func Ontology() *owl.Ontology {
	o, err := owl.ParseFunctionalString(source)
	if err != nil {
		panic("time: generated ontology does not parse: " + err.Error())
	}
	return o
}

// Vocabulary returns the terms this vocabulary declares, with their labels and
// definitions, as the closed set an untrusted axiom can be validated against.
// Terms it only references — another vocabulary's, named to relate the two —
// are not part of it. It is built once and is safe to share.
func Vocabulary() *owl.Vocabulary { return vocabulary() }

var vocabulary = sync.OnceValue(func() *owl.Vocabulary {
	return owl.NewVocabulary(Ontology(), owl.DeclaredOnly())
})
