// Code generated by cmd/vocabgen. DO NOT EDIT.

// Package foaf is the FOAF vocabulary as OWL entities.
//
// Friend of a Friend: people, the accounts and documents they hold, and
// the links between them. The oldest widely deployed vocabulary for
// describing agents on the web.
//
// Each term is a typed constant, so the compiler keeps a class out of a
// property's place. [Ontology] returns the axioms the vocabulary asserts
// about them, and [Vocabulary] the same terms with their labels attached.
//
// Source: http://xmlns.com/foaf/spec/index.rdf
// SHA-256: 3d859b5d92a2c3d041545d014fa826f682ca06d056af8c7b31e32d930abf2bc5
package foaf

import (
	_ "embed"
	"sync"

	"gowl/owl"
)

// Prefix and Namespace are the vocabulary's customary prefix and the IRI it
// abbreviates.
const (
	Prefix            = "foaf"
	Namespace owl.IRI = "http://xmlns.com/foaf/0.1/"
)

// Classes.
const (
	// Agent is foaf:Agent.
	//
	// An agent (eg. person, group, software or physical artifact).
	Agent owl.Class = "http://xmlns.com/foaf/0.1/Agent"

	// Document is foaf:Document.
	//
	// A document.
	Document owl.Class = "http://xmlns.com/foaf/0.1/Document"

	// Group is foaf:Group.
	//
	// A class of Agents.
	Group owl.Class = "http://xmlns.com/foaf/0.1/Group"

	// Image is foaf:Image.
	//
	// An image.
	Image owl.Class = "http://xmlns.com/foaf/0.1/Image"

	// LabelProperty is foaf:LabelProperty, "Label Property".
	//
	// A foaf:LabelProperty is any RDF property with texual values that serve
	// as labels.
	LabelProperty owl.Class = "http://xmlns.com/foaf/0.1/LabelProperty"

	// OnlineAccount is foaf:OnlineAccount, "Online Account".
	//
	// An online account.
	OnlineAccount owl.Class = "http://xmlns.com/foaf/0.1/OnlineAccount"

	// OnlineChatAccount is foaf:OnlineChatAccount, "Online Chat Account".
	//
	// An online chat account.
	OnlineChatAccount owl.Class = "http://xmlns.com/foaf/0.1/OnlineChatAccount"

	// OnlineEcommerceAccount is foaf:OnlineEcommerceAccount, "Online
	// E-commerce Account".
	//
	// An online e-commerce account.
	OnlineEcommerceAccount owl.Class = "http://xmlns.com/foaf/0.1/OnlineEcommerceAccount"

	// OnlineGamingAccount is foaf:OnlineGamingAccount, "Online Gaming
	// Account".
	//
	// An online gaming account.
	OnlineGamingAccount owl.Class = "http://xmlns.com/foaf/0.1/OnlineGamingAccount"

	// Organization is foaf:Organization.
	//
	// An organization.
	Organization owl.Class = "http://xmlns.com/foaf/0.1/Organization"

	// Person is foaf:Person.
	//
	// A person.
	Person owl.Class = "http://xmlns.com/foaf/0.1/Person"

	// PersonalProfileDocument is foaf:PersonalProfileDocument.
	//
	// A personal profile RDF document.
	PersonalProfileDocument owl.Class = "http://xmlns.com/foaf/0.1/PersonalProfileDocument"

	// Project is foaf:Project.
	//
	// A project (a collective endeavour of some kind).
	Project owl.Class = "http://xmlns.com/foaf/0.1/Project"
)

// Object properties.
const (
	// Account is foaf:account.
	//
	// Indicates an account held by this agent.
	Account owl.ObjectProperty = "http://xmlns.com/foaf/0.1/account"

	// AccountServiceHomepage is foaf:accountServiceHomepage, "account service
	// homepage".
	//
	// Indicates a homepage of the service provide for this online account.
	AccountServiceHomepage owl.ObjectProperty = "http://xmlns.com/foaf/0.1/accountServiceHomepage"

	// AimChatID is foaf:aimChatID, "AIM chat ID".
	//
	// An AIM chat ID
	AimChatID owl.ObjectProperty = "http://xmlns.com/foaf/0.1/aimChatID"

	// BasedNear is foaf:based_near, "based near".
	//
	// A location that something is based near, for some broadly human notion
	// of near.
	BasedNear owl.ObjectProperty = "http://xmlns.com/foaf/0.1/based_near"

	// CurrentProject is foaf:currentProject, "current project".
	//
	// A current project this person works on.
	CurrentProject owl.ObjectProperty = "http://xmlns.com/foaf/0.1/currentProject"

	// Depiction is foaf:depiction.
	//
	// A depiction of some thing.
	Depiction owl.ObjectProperty = "http://xmlns.com/foaf/0.1/depiction"

	// Depicts is foaf:depicts.
	//
	// A thing depicted in this representation.
	Depicts owl.ObjectProperty = "http://xmlns.com/foaf/0.1/depicts"

	// Focus is foaf:focus.
	//
	// The underlying or 'focal' entity associated with some SKOS-described
	// concept.
	Focus owl.ObjectProperty = "http://xmlns.com/foaf/0.1/focus"

	// FundedBy is foaf:fundedBy, "funded by".
	//
	// An organization funding a project or person.
	FundedBy owl.ObjectProperty = "http://xmlns.com/foaf/0.1/fundedBy"

	// HoldsAccount is foaf:holdsAccount, "account".
	//
	// Indicates an account held by this agent.
	HoldsAccount owl.ObjectProperty = "http://xmlns.com/foaf/0.1/holdsAccount"

	// Homepage is foaf:homepage.
	//
	// A homepage for some thing.
	Homepage owl.ObjectProperty = "http://xmlns.com/foaf/0.1/homepage"

	// IcqChatID is foaf:icqChatID, "ICQ chat ID".
	//
	// An ICQ chat ID
	IcqChatID owl.ObjectProperty = "http://xmlns.com/foaf/0.1/icqChatID"

	// Img is foaf:img, "image".
	//
	// An image that can be used to represent some thing (ie. those depictions
	// which are particularly representative of something, eg. one's photo on a
	// homepage).
	Img owl.ObjectProperty = "http://xmlns.com/foaf/0.1/img"

	// Interest is foaf:interest.
	//
	// A page about a topic of interest to this person.
	Interest owl.ObjectProperty = "http://xmlns.com/foaf/0.1/interest"

	// IsPrimaryTopicOf is foaf:isPrimaryTopicOf, "is primary topic of".
	//
	// A document that this thing is the primary topic of.
	IsPrimaryTopicOf owl.ObjectProperty = "http://xmlns.com/foaf/0.1/isPrimaryTopicOf"

	// JabberID is foaf:jabberID, "jabber ID".
	//
	// A jabber ID for something.
	JabberID owl.ObjectProperty = "http://xmlns.com/foaf/0.1/jabberID"

	// Knows is foaf:knows.
	//
	// A person known by this person (indicating some level of reciprocated
	// interaction between the parties).
	Knows owl.ObjectProperty = "http://xmlns.com/foaf/0.1/knows"

	// Logo is foaf:logo.
	//
	// A logo representing some thing.
	Logo owl.ObjectProperty = "http://xmlns.com/foaf/0.1/logo"

	// Made is foaf:made.
	//
	// Something that was made by this agent.
	Made owl.ObjectProperty = "http://xmlns.com/foaf/0.1/made"

	// Maker is foaf:maker.
	//
	// An agent that made this thing.
	Maker owl.ObjectProperty = "http://xmlns.com/foaf/0.1/maker"

	// Mbox is foaf:mbox, "personal mailbox".
	//
	// A personal mailbox, ie. an Internet mailbox associated with exactly one
	// owner, the first owner of this mailbox. This is a 'static inverse
	// functional property', in that there is (across time and change) at most
	// one individual that ever has any particular value for foaf:mbox.
	Mbox owl.ObjectProperty = "http://xmlns.com/foaf/0.1/mbox"

	// MboxSha1sum is foaf:mbox_sha1sum, "sha1sum of a personal mailbox URI
	// name".
	//
	// The sha1sum of the URI of an Internet mailbox associated with exactly
	// one owner, the first owner of the mailbox.
	MboxSha1sum owl.ObjectProperty = "http://xmlns.com/foaf/0.1/mbox_sha1sum"

	// Member is foaf:member.
	//
	// Indicates a member of a Group
	Member owl.ObjectProperty = "http://xmlns.com/foaf/0.1/member"

	// MsnChatID is foaf:msnChatID, "MSN chat ID".
	//
	// An MSN chat ID
	MsnChatID owl.ObjectProperty = "http://xmlns.com/foaf/0.1/msnChatID"

	// Openid is foaf:openid.
	//
	// An OpenID for an Agent.
	Openid owl.ObjectProperty = "http://xmlns.com/foaf/0.1/openid"

	// Page is foaf:page.
	//
	// A page or document about this thing.
	Page owl.ObjectProperty = "http://xmlns.com/foaf/0.1/page"

	// PastProject is foaf:pastProject, "past project".
	//
	// A project this person has previously worked on.
	PastProject owl.ObjectProperty = "http://xmlns.com/foaf/0.1/pastProject"

	// Phone is foaf:phone.
	//
	// A phone, specified using fully qualified tel: URI scheme (refs:
	// http://www.w3.org/Addressing/schemes.html#tel).
	Phone owl.ObjectProperty = "http://xmlns.com/foaf/0.1/phone"

	// PrimaryTopic is foaf:primaryTopic, "primary topic".
	//
	// The primary topic of some page or document.
	PrimaryTopic owl.ObjectProperty = "http://xmlns.com/foaf/0.1/primaryTopic"

	// Publications is foaf:publications.
	//
	// A link to the publications of this person.
	Publications owl.ObjectProperty = "http://xmlns.com/foaf/0.1/publications"

	// SchoolHomepage is foaf:schoolHomepage.
	//
	// A homepage of a school attended by the person.
	SchoolHomepage owl.ObjectProperty = "http://xmlns.com/foaf/0.1/schoolHomepage"

	// Theme is foaf:theme.
	//
	// A theme.
	Theme owl.ObjectProperty = "http://xmlns.com/foaf/0.1/theme"

	// Thumbnail is foaf:thumbnail.
	//
	// A derived thumbnail image.
	Thumbnail owl.ObjectProperty = "http://xmlns.com/foaf/0.1/thumbnail"

	// Tipjar is foaf:tipjar.
	//
	// A tipjar document for this agent, describing means for payment and
	// reward.
	Tipjar owl.ObjectProperty = "http://xmlns.com/foaf/0.1/tipjar"

	// Topic is foaf:topic.
	//
	// A topic of some page or document.
	Topic owl.ObjectProperty = "http://xmlns.com/foaf/0.1/topic"

	// TopicInterest is foaf:topic_interest.
	//
	// A thing of interest to this person.
	TopicInterest owl.ObjectProperty = "http://xmlns.com/foaf/0.1/topic_interest"

	// Weblog is foaf:weblog.
	//
	// A weblog of some thing (whether person, group, company etc.).
	Weblog owl.ObjectProperty = "http://xmlns.com/foaf/0.1/weblog"

	// WorkInfoHomepage is foaf:workInfoHomepage, "work info homepage".
	//
	// A work info homepage of some person; a page about their work for some
	// organization.
	WorkInfoHomepage owl.ObjectProperty = "http://xmlns.com/foaf/0.1/workInfoHomepage"

	// WorkplaceHomepage is foaf:workplaceHomepage, "workplace homepage".
	//
	// A workplace homepage of some person; the homepage of an organization
	// they work for.
	WorkplaceHomepage owl.ObjectProperty = "http://xmlns.com/foaf/0.1/workplaceHomepage"

	// YahooChatID is foaf:yahooChatID, "Yahoo chat ID".
	//
	// A Yahoo chat ID
	YahooChatID owl.ObjectProperty = "http://xmlns.com/foaf/0.1/yahooChatID"
)

// Data properties.
const (
	// AccountName is foaf:accountName, "account name".
	//
	// Indicates the name (identifier) associated with this online account.
	AccountName owl.DataProperty = "http://xmlns.com/foaf/0.1/accountName"

	// Age is foaf:age.
	//
	// The age in years of some agent.
	Age owl.DataProperty = "http://xmlns.com/foaf/0.1/age"

	// AimChatIDDataProperty is foaf:aimChatID, "AIM chat ID".
	//
	// An AIM chat ID
	AimChatIDDataProperty owl.DataProperty = "http://xmlns.com/foaf/0.1/aimChatID"

	// Birthday is foaf:birthday.
	//
	// The birthday of this Agent, represented in mm-dd string form, eg.
	// '12-31'.
	Birthday owl.DataProperty = "http://xmlns.com/foaf/0.1/birthday"

	// DnaChecksum is foaf:dnaChecksum, "DNA checksum".
	//
	// A checksum for the DNA of some thing. Joke.
	DnaChecksum owl.DataProperty = "http://xmlns.com/foaf/0.1/dnaChecksum"

	// FamilyName is foaf:familyName.
	//
	// The family name of some person.
	FamilyName owl.DataProperty = "http://xmlns.com/foaf/0.1/familyName"

	// FamilyNameDataProperty is foaf:family_name.
	//
	// The family name of some person.
	FamilyNameDataProperty owl.DataProperty = "http://xmlns.com/foaf/0.1/family_name"

	// FirstName is foaf:firstName.
	//
	// The first name of a person.
	FirstName owl.DataProperty = "http://xmlns.com/foaf/0.1/firstName"

	// Geekcode is foaf:geekcode.
	//
	// A textual geekcode for this person, see
	// http://www.geekcode.com/geek.html
	Geekcode owl.DataProperty = "http://xmlns.com/foaf/0.1/geekcode"

	// Gender is foaf:gender.
	//
	// The gender of this Agent (typically but not necessarily 'male' or
	// 'female').
	Gender owl.DataProperty = "http://xmlns.com/foaf/0.1/gender"

	// GivenName is foaf:givenName, "Given name".
	//
	// The given name of some person.
	GivenName owl.DataProperty = "http://xmlns.com/foaf/0.1/givenName"

	// Givenname is foaf:givenname, "Given name".
	//
	// The given name of some person.
	Givenname owl.DataProperty = "http://xmlns.com/foaf/0.1/givenname"

	// IcqChatIDDataProperty is foaf:icqChatID, "ICQ chat ID".
	//
	// An ICQ chat ID
	IcqChatIDDataProperty owl.DataProperty = "http://xmlns.com/foaf/0.1/icqChatID"

	// JabberIDDataProperty is foaf:jabberID, "jabber ID".
	//
	// A jabber ID for something.
	JabberIDDataProperty owl.DataProperty = "http://xmlns.com/foaf/0.1/jabberID"

	// LastName is foaf:lastName.
	//
	// The last name of a person.
	LastName owl.DataProperty = "http://xmlns.com/foaf/0.1/lastName"

	// MboxSha1sumDataProperty is foaf:mbox_sha1sum, "sha1sum of a personal
	// mailbox URI name".
	//
	// The sha1sum of the URI of an Internet mailbox associated with exactly
	// one owner, the first owner of the mailbox.
	MboxSha1sumDataProperty owl.DataProperty = "http://xmlns.com/foaf/0.1/mbox_sha1sum"

	// MsnChatIDDataProperty is foaf:msnChatID, "MSN chat ID".
	//
	// An MSN chat ID
	MsnChatIDDataProperty owl.DataProperty = "http://xmlns.com/foaf/0.1/msnChatID"

	// MyersBriggs is foaf:myersBriggs.
	//
	// A Myers Briggs (MBTI) personality classification.
	MyersBriggs owl.DataProperty = "http://xmlns.com/foaf/0.1/myersBriggs"

	// Name is foaf:name.
	//
	// A name for some thing.
	Name owl.DataProperty = "http://xmlns.com/foaf/0.1/name"

	// Nick is foaf:nick, "nickname".
	//
	// A short informal nickname characterising an agent (includes login
	// identifiers, IRC and other chat nicknames).
	Nick owl.DataProperty = "http://xmlns.com/foaf/0.1/nick"

	// Plan is foaf:plan.
	//
	// A .plan comment, in the tradition of finger and '.plan' files.
	Plan owl.DataProperty = "http://xmlns.com/foaf/0.1/plan"

	// Sha1 is foaf:sha1, "sha1sum (hex)".
	//
	// A sha1sum hash, in hex.
	Sha1 owl.DataProperty = "http://xmlns.com/foaf/0.1/sha1"

	// SkypeID is foaf:skypeID, "Skype ID".
	//
	// A Skype ID
	SkypeID owl.DataProperty = "http://xmlns.com/foaf/0.1/skypeID"

	// Status is foaf:status.
	//
	// A string expressing what the user is happy for the general public
	// (normally) to know about their current activity.
	Status owl.DataProperty = "http://xmlns.com/foaf/0.1/status"

	// Surname is foaf:surname.
	//
	// The surname of some person.
	Surname owl.DataProperty = "http://xmlns.com/foaf/0.1/surname"

	// Title is foaf:title.
	//
	// Title (Mr, Mrs, Ms, Dr. etc)
	Title owl.DataProperty = "http://xmlns.com/foaf/0.1/title"

	// YahooChatIDDataProperty is foaf:yahooChatID, "Yahoo chat ID".
	//
	// A Yahoo chat ID
	YahooChatIDDataProperty owl.DataProperty = "http://xmlns.com/foaf/0.1/yahooChatID"
)

// Annotation properties.
const (
	// MembershipClass is foaf:membershipClass.
	//
	// Indicates the class of individuals that are a member of a Group
	MembershipClass owl.AnnotationProperty = "http://xmlns.com/foaf/0.1/membershipClass"
)

//go:embed foaf.ofn
var source string

// Ontology returns the vocabulary's axioms: its declarations, its class and
// property hierarchy, and the labels and definitions its authors wrote.
//
// Each call parses a fresh ontology, so the result is the caller's to add to
// or rewrite. Use [Vocabulary] instead to look terms up without copying.
func Ontology() *owl.Ontology {
	o, err := owl.ParseFunctionalString(source)
	if err != nil {
		panic("foaf: generated ontology does not parse: " + err.Error())
	}
	return o
}

// Vocabulary returns the terms with their labels and definitions, as the
// closed set an untrusted axiom can be validated against. It is built once and
// is safe to share.
func Vocabulary() *owl.Vocabulary { return vocabulary() }

var vocabulary = sync.OnceValue(func() *owl.Vocabulary {
	return owl.NewVocabulary(Ontology())
})
