// Code generated by cmd/vocabgen. DO NOT EDIT.

// Package skos is the SKOS Core vocabulary as OWL entities.
//
// Simple Knowledge Organization System: concepts, concept schemes and the
// broader/narrower/related relations that thesauri, taxonomies and subject
// heading lists are built from. A W3C Recommendation since 2009.
//
// Each term is a typed constant, so the compiler keeps a class out of a
// property's place. [Ontology] returns the axioms the vocabulary asserts
// about them, and [Vocabulary] the same terms with their labels attached.
//
// Source: https://www.w3.org/2009/08/skos-reference/skos.rdf
// SHA-256: e79633b8d0564816cee8a99f5c9acf9a0e6fc7257c7209acd684ecad53a89dd6
package skos

import (
	_ "embed"
	"sync"

	"gowl/owl"
)

// Prefix and Namespace are the vocabulary's customary prefix and the IRI it
// abbreviates.
const (
	Prefix            = "skos"
	Namespace owl.IRI = "http://www.w3.org/2004/02/skos/core#"
)

// Classes.
const (
	// Collection is skos:Collection.
	//
	// A meaningful collection of concepts.
	Collection owl.Class = "http://www.w3.org/2004/02/skos/core#Collection"

	// Concept is skos:Concept.
	//
	// An idea or notion; a unit of thought.
	Concept owl.Class = "http://www.w3.org/2004/02/skos/core#Concept"

	// ConceptScheme is skos:ConceptScheme, "Concept Scheme".
	//
	// A set of concepts, optionally including statements about semantic
	// relationships between those concepts.
	ConceptScheme owl.Class = "http://www.w3.org/2004/02/skos/core#ConceptScheme"

	// OrderedCollection is skos:OrderedCollection, "Ordered Collection".
	//
	// An ordered collection of concepts, where both the grouping and the
	// ordering are meaningful.
	OrderedCollection owl.Class = "http://www.w3.org/2004/02/skos/core#OrderedCollection"
)

// Object properties.
const (
	// BroadMatch is skos:broadMatch, "has broader match".
	//
	// skos:broadMatch is used to state a hierarchical mapping link between two
	// conceptual resources in different concept schemes.
	BroadMatch owl.ObjectProperty = "http://www.w3.org/2004/02/skos/core#broadMatch"

	// Broader is skos:broader, "has broader".
	//
	// Broader concepts are typically rendered as parents in a concept
	// hierarchy (tree).
	Broader owl.ObjectProperty = "http://www.w3.org/2004/02/skos/core#broader"

	// BroaderTransitive is skos:broaderTransitive, "has broader transitive".
	//
	// skos:broaderTransitive is a transitive superproperty of skos:broader.
	BroaderTransitive owl.ObjectProperty = "http://www.w3.org/2004/02/skos/core#broaderTransitive"

	// CloseMatch is skos:closeMatch, "has close match".
	//
	// skos:closeMatch is used to link two concepts that are sufficiently
	// similar that they can be used interchangeably in some information
	// retrieval applications. In order to avoid the possibility of "compound
	// errors" when combining mappings across more than two concept schemes,
	// skos:closeMatch is not declared to be a transitive property.
	CloseMatch owl.ObjectProperty = "http://www.w3.org/2004/02/skos/core#closeMatch"

	// ExactMatch is skos:exactMatch, "has exact match".
	//
	// skos:exactMatch is disjoint with each of the properties skos:broadMatch
	// and skos:relatedMatch.
	ExactMatch owl.ObjectProperty = "http://www.w3.org/2004/02/skos/core#exactMatch"

	// HasTopConcept is skos:hasTopConcept, "has top concept".
	//
	// Relates, by convention, a concept scheme to a concept which is topmost
	// in the broader/narrower concept hierarchies for that scheme, providing
	// an entry point to these hierarchies.
	HasTopConcept owl.ObjectProperty = "http://www.w3.org/2004/02/skos/core#hasTopConcept"

	// InScheme is skos:inScheme, "is in scheme".
	//
	// Relates a resource (for example a concept) to a concept scheme in which
	// it is included.
	InScheme owl.ObjectProperty = "http://www.w3.org/2004/02/skos/core#inScheme"

	// MappingRelation is skos:mappingRelation, "is in mapping relation with".
	//
	// These concept mapping relations mirror semantic relations, and the data
	// model defined below is similar (with the exception of skos:exactMatch)
	// to the data model defined for semantic relations. A distinct vocabulary
	// is provided for concept mapping relations, to provide a convenient way
	// to differentiate links within a concept scheme from links between
	// concept schemes. However, this pattern of usage is not a formal
	// requirement of the SKOS data model, and relies on informal definitions
	// of best practice.
	MappingRelation owl.ObjectProperty = "http://www.w3.org/2004/02/skos/core#mappingRelation"

	// Member is skos:member, "has member".
	//
	// Relates a collection to one of its members.
	Member owl.ObjectProperty = "http://www.w3.org/2004/02/skos/core#member"

	// MemberList is skos:memberList, "has member list".
	//
	// For any resource, every item in the list given as the value of the
	// skos:memberList property is also a value of the skos:member property.
	MemberList owl.ObjectProperty = "http://www.w3.org/2004/02/skos/core#memberList"

	// NarrowMatch is skos:narrowMatch, "has narrower match".
	//
	// skos:narrowMatch is used to state a hierarchical mapping link between
	// two conceptual resources in different concept schemes.
	NarrowMatch owl.ObjectProperty = "http://www.w3.org/2004/02/skos/core#narrowMatch"

	// Narrower is skos:narrower, "has narrower".
	//
	// Narrower concepts are typically rendered as children in a concept
	// hierarchy (tree).
	Narrower owl.ObjectProperty = "http://www.w3.org/2004/02/skos/core#narrower"

	// NarrowerTransitive is skos:narrowerTransitive, "has narrower
	// transitive".
	//
	// skos:narrowerTransitive is a transitive superproperty of skos:narrower.
	NarrowerTransitive owl.ObjectProperty = "http://www.w3.org/2004/02/skos/core#narrowerTransitive"

	// Related is skos:related, "has related".
	//
	// skos:related is disjoint with skos:broaderTransitive
	Related owl.ObjectProperty = "http://www.w3.org/2004/02/skos/core#related"

	// RelatedMatch is skos:relatedMatch, "has related match".
	//
	// skos:relatedMatch is used to state an associative mapping link between
	// two conceptual resources in different concept schemes.
	RelatedMatch owl.ObjectProperty = "http://www.w3.org/2004/02/skos/core#relatedMatch"

	// SemanticRelation is skos:semanticRelation, "is in semantic relation
	// with".
	//
	// Links a concept to a concept related by meaning.
	SemanticRelation owl.ObjectProperty = "http://www.w3.org/2004/02/skos/core#semanticRelation"

	// TopConceptOf is skos:topConceptOf, "is top concept in scheme".
	//
	// Relates a concept to the concept scheme that it is a top level concept
	// of.
	TopConceptOf owl.ObjectProperty = "http://www.w3.org/2004/02/skos/core#topConceptOf"
)

// Data properties.
const (
	// Notation is skos:notation.
	//
	// A notation, also known as classification code, is a string of characters
	// such as "T58.5" or "303.4833" used to uniquely identify a concept within
	// the scope of a given concept scheme.
	Notation owl.DataProperty = "http://www.w3.org/2004/02/skos/core#notation"
)

// Annotation properties.
const (
	// AltLabel is skos:altLabel, "alternative label".
	//
	// The range of skos:altLabel is the class of RDF plain literals.
	AltLabel owl.AnnotationProperty = "http://www.w3.org/2004/02/skos/core#altLabel"

	// ChangeNote is skos:changeNote, "change note".
	//
	// A note about a modification to a concept.
	ChangeNote owl.AnnotationProperty = "http://www.w3.org/2004/02/skos/core#changeNote"

	// Definition is skos:definition.
	//
	// A statement or formal explanation of the meaning of a concept.
	Definition owl.AnnotationProperty = "http://www.w3.org/2004/02/skos/core#definition"

	// EditorialNote is skos:editorialNote, "editorial note".
	//
	// A note for an editor, translator or maintainer of the vocabulary.
	EditorialNote owl.AnnotationProperty = "http://www.w3.org/2004/02/skos/core#editorialNote"

	// Example is skos:example.
	//
	// An example of the use of a concept.
	Example owl.AnnotationProperty = "http://www.w3.org/2004/02/skos/core#example"

	// HiddenLabel is skos:hiddenLabel, "hidden label".
	//
	// The range of skos:hiddenLabel is the class of RDF plain literals.
	HiddenLabel owl.AnnotationProperty = "http://www.w3.org/2004/02/skos/core#hiddenLabel"

	// HistoryNote is skos:historyNote, "history note".
	//
	// A note about the past state/use/meaning of a concept.
	HistoryNote owl.AnnotationProperty = "http://www.w3.org/2004/02/skos/core#historyNote"

	// Note is skos:note.
	//
	// A general note, for any purpose.
	Note owl.AnnotationProperty = "http://www.w3.org/2004/02/skos/core#note"

	// PrefLabel is skos:prefLabel, "preferred label".
	//
	// A resource has no more than one value of skos:prefLabel per language
	// tag, and no more than one value of skos:prefLabel without language tag.
	PrefLabel owl.AnnotationProperty = "http://www.w3.org/2004/02/skos/core#prefLabel"

	// ScopeNote is skos:scopeNote, "scope note".
	//
	// A note that helps to clarify the meaning and/or the use of a concept.
	ScopeNote owl.AnnotationProperty = "http://www.w3.org/2004/02/skos/core#scopeNote"
)

//go:embed skos.ofn
var source string

// Ontology returns the vocabulary's axioms: its declarations, its class and
// property hierarchy, and the labels and definitions its authors wrote.
//
// Each call parses a fresh ontology, so the result is the caller's to add to
// or rewrite. Use [Vocabulary] instead to look terms up without copying.
func Ontology() *owl.Ontology {
	o, err := owl.ParseFunctionalString(source)
	if err != nil {
		panic("skos: generated ontology does not parse: " + err.Error())
	}
	return o
}

// Vocabulary returns the terms this vocabulary declares, with their labels and
// definitions, as the closed set an untrusted axiom can be validated against.
// Terms it only references — another vocabulary's, named to relate the two —
// are not part of it. It is built once and is safe to share.
func Vocabulary() *owl.Vocabulary { return vocabulary() }

var vocabulary = sync.OnceValue(func() *owl.Vocabulary {
	return owl.NewVocabulary(Ontology(), owl.DeclaredOnly())
})
