// Code generated by cmd/vocabgen. DO NOT EDIT.

// Package rdfs is the RDF Schema vocabulary as OWL entities.
//
// RDF Schema: classes, properties, the subclass and subproperty relations,
// and the annotation properties every other vocabulary on this list is
// documented with.
//
// Each term is a typed constant, so the compiler keeps a class out of a
// property's place. [Ontology] returns the axioms the vocabulary asserts
// about them, and [Vocabulary] the same terms with their labels attached.
//
// Source: http://www.w3.org/2000/01/rdf-schema
// SHA-256: ecee3a011b7c13ea2a7e40b0a208bfe6be53d69fdd53ee035e09e9f9e5108ad6
package rdfs

import (
	_ "embed"
	"sync"

	"gowl/owl"
)

// Prefix and Namespace are the vocabulary's customary prefix and the IRI it
// abbreviates.
const (
	Prefix            = "rdfs"
	Namespace owl.IRI = "http://www.w3.org/2000/01/rdf-schema#"
)

// Classes.
const (
	// Class is rdfs:Class.
	//
	// The class of classes.
	Class owl.Class = "http://www.w3.org/2000/01/rdf-schema#Class"

	// Container is rdfs:Container.
	//
	// The class of RDF containers.
	Container owl.Class = "http://www.w3.org/2000/01/rdf-schema#Container"

	// ContainerMembershipProperty is rdfs:ContainerMembershipProperty.
	//
	// The class of container membership properties, rdf:_1, rdf:_2, ..., all
	// of which are sub-properties of 'member'.
	ContainerMembershipProperty owl.Class = "http://www.w3.org/2000/01/rdf-schema#ContainerMembershipProperty"

	// Datatype is rdfs:Datatype.
	//
	// The class of RDF datatypes.
	Datatype owl.Class = "http://www.w3.org/2000/01/rdf-schema#Datatype"

	// Resource is rdfs:Resource.
	//
	// The class resource, everything.
	Resource owl.Class = "http://www.w3.org/2000/01/rdf-schema#Resource"
)

// Datatypes.
const (
	// Literal is rdfs:Literal.
	//
	// The class of literal values, eg. textual strings and integers.
	Literal owl.Datatype = "http://www.w3.org/2000/01/rdf-schema#Literal"
)

// Object properties.
const (
	// Domain is rdfs:domain.
	//
	// A domain of the subject property.
	Domain owl.ObjectProperty = "http://www.w3.org/2000/01/rdf-schema#domain"

	// Member is rdfs:member.
	//
	// A member of the subject resource.
	Member owl.ObjectProperty = "http://www.w3.org/2000/01/rdf-schema#member"

	// Range is rdfs:range.
	//
	// A range of the subject property.
	Range owl.ObjectProperty = "http://www.w3.org/2000/01/rdf-schema#range"

	// SubClassOf is rdfs:subClassOf.
	//
	// The subject is a subclass of a class.
	SubClassOf owl.ObjectProperty = "http://www.w3.org/2000/01/rdf-schema#subClassOf"

	// SubPropertyOf is rdfs:subPropertyOf.
	//
	// The subject is a subproperty of a property.
	SubPropertyOf owl.ObjectProperty = "http://www.w3.org/2000/01/rdf-schema#subPropertyOf"
)

// Annotation properties.
const (
	// Comment is rdfs:comment.
	//
	// A description of the subject resource.
	Comment owl.AnnotationProperty = "http://www.w3.org/2000/01/rdf-schema#comment"

	// IsDefinedBy is rdfs:isDefinedBy.
	//
	// The definition of the subject resource.
	IsDefinedBy owl.AnnotationProperty = "http://www.w3.org/2000/01/rdf-schema#isDefinedBy"

	// Label is rdfs:label.
	//
	// A human-readable name for the subject.
	Label owl.AnnotationProperty = "http://www.w3.org/2000/01/rdf-schema#label"

	// SeeAlso is rdfs:seeAlso.
	//
	// Further information about the subject resource.
	SeeAlso owl.AnnotationProperty = "http://www.w3.org/2000/01/rdf-schema#seeAlso"
)

//go:embed rdfs.ofn
var source string

// Ontology returns the vocabulary's axioms: its declarations, its class and
// property hierarchy, and the labels and definitions its authors wrote.
//
// Each call parses a fresh ontology, so the result is the caller's to add to
// or rewrite. Use [Vocabulary] instead to look terms up without copying.
func Ontology() *owl.Ontology {
	o, err := owl.ParseFunctionalString(source)
	if err != nil {
		panic("rdfs: generated ontology does not parse: " + err.Error())
	}
	return o
}

// Vocabulary returns the terms this vocabulary declares, with their labels and
// definitions, as the closed set an untrusted axiom can be validated against.
// Terms it only references — another vocabulary's, named to relate the two —
// are not part of it. It is built once and is safe to share.
func Vocabulary() *owl.Vocabulary { return vocabulary() }

var vocabulary = sync.OnceValue(func() *owl.Vocabulary {
	return owl.NewVocabulary(Ontology(), owl.DeclaredOnly(), owl.WithBuiltins())
})
