// Code generated by cmd/vocabgen. DO NOT EDIT.

// Package rdf is the RDF vocabulary as OWL entities.
//
// The terms RDF itself defines: rdf:type, the container membership
// properties, the reification vocabulary and the datatypes RDF 1.1 adds to
// XML Schema.
//
// Each term is a typed constant, so the compiler keeps a class out of a
// property's place. [Ontology] returns the axioms the vocabulary asserts
// about them, and [Vocabulary] the same terms with their labels attached.
//
// Source: http://www.w3.org/1999/02/22-rdf-syntax-ns
// SHA-256: 93d52b1a5824c7dd6504ca79c16205c0b740a0ba68b7a14952780f52561186a2
package rdf

import (
	_ "embed"
	"sync"

	"gowl/owl"
)

// Prefix and Namespace are the vocabulary's customary prefix and the IRI it
// abbreviates.
const (
	Prefix            = "rdf"
	Namespace owl.IRI = "http://www.w3.org/1999/02/22-rdf-syntax-ns#"
)

// Classes.
const (
	// Alt is rdf:Alt.
	//
	// The class of containers of alternatives.
	Alt owl.Class = "http://www.w3.org/1999/02/22-rdf-syntax-ns#Alt"

	// Bag is rdf:Bag.
	//
	// The class of unordered containers.
	Bag owl.Class = "http://www.w3.org/1999/02/22-rdf-syntax-ns#Bag"

	// CompoundLiteral is rdf:CompoundLiteral.
	//
	// A class representing a compound literal.
	CompoundLiteral owl.Class = "http://www.w3.org/1999/02/22-rdf-syntax-ns#CompoundLiteral"

	// List is rdf:List.
	//
	// The class of RDF Lists.
	List owl.Class = "http://www.w3.org/1999/02/22-rdf-syntax-ns#List"

	// Property is rdf:Property.
	//
	// The class of RDF properties.
	Property owl.Class = "http://www.w3.org/1999/02/22-rdf-syntax-ns#Property"

	// Seq is rdf:Seq.
	//
	// The class of ordered containers.
	Seq owl.Class = "http://www.w3.org/1999/02/22-rdf-syntax-ns#Seq"

	// Statement is rdf:Statement.
	//
	// The class of RDF statements.
	Statement owl.Class = "http://www.w3.org/1999/02/22-rdf-syntax-ns#Statement"
)

// Datatypes.
const (
	// HTML is rdf:HTML.
	//
	// The datatype of RDF literals storing fragments of HTML content
	HTML owl.Datatype = "http://www.w3.org/1999/02/22-rdf-syntax-ns#HTML"

	// JSON is rdf:JSON.
	//
	// The datatype of RDF literals storing JSON content.
	JSON owl.Datatype = "http://www.w3.org/1999/02/22-rdf-syntax-ns#JSON"

	// PlainLiteral is rdf:PlainLiteral.
	//
	// The class of plain (i.e. untyped) literal values, as used in RIF and OWL
	// 2
	PlainLiteral owl.Datatype = "http://www.w3.org/1999/02/22-rdf-syntax-ns#PlainLiteral"

	// XMLLiteral is rdf:XMLLiteral.
	//
	// The datatype of XML literal values.
	XMLLiteral owl.Datatype = "http://www.w3.org/1999/02/22-rdf-syntax-ns#XMLLiteral"

	// LangString is rdf:langString.
	//
	// The datatype of language-tagged string values
	LangString owl.Datatype = "http://www.w3.org/1999/02/22-rdf-syntax-ns#langString"
)

// Object properties.
const (
	// Direction is rdf:direction.
	//
	// The base direction component of a CompoundLiteral.
	Direction owl.ObjectProperty = "http://www.w3.org/1999/02/22-rdf-syntax-ns#direction"

	// First is rdf:first.
	//
	// The first item in the subject RDF list.
	First owl.ObjectProperty = "http://www.w3.org/1999/02/22-rdf-syntax-ns#first"

	// Language is rdf:language.
	//
	// The language component of a CompoundLiteral.
	Language owl.ObjectProperty = "http://www.w3.org/1999/02/22-rdf-syntax-ns#language"

	// Object is rdf:object.
	//
	// The object of the subject RDF statement.
	Object owl.ObjectProperty = "http://www.w3.org/1999/02/22-rdf-syntax-ns#object"

	// Predicate is rdf:predicate.
	//
	// The predicate of the subject RDF statement.
	Predicate owl.ObjectProperty = "http://www.w3.org/1999/02/22-rdf-syntax-ns#predicate"

	// Rest is rdf:rest.
	//
	// The rest of the subject RDF list after the first item.
	Rest owl.ObjectProperty = "http://www.w3.org/1999/02/22-rdf-syntax-ns#rest"

	// Subject is rdf:subject.
	//
	// The subject of the subject RDF statement.
	Subject owl.ObjectProperty = "http://www.w3.org/1999/02/22-rdf-syntax-ns#subject"

	// Type is rdf:type.
	//
	// The subject is an instance of a class.
	Type owl.ObjectProperty = "http://www.w3.org/1999/02/22-rdf-syntax-ns#type"

	// Value is rdf:value.
	//
	// Idiomatic property used for structured values.
	Value owl.ObjectProperty = "http://www.w3.org/1999/02/22-rdf-syntax-ns#value"
)

// Individuals.
const (
	// Nil is rdf:nil.
	//
	// The empty list, with no items in it. If the rest of a list is nil then
	// the list has no more items in it.
	Nil owl.NamedIndividual = "http://www.w3.org/1999/02/22-rdf-syntax-ns#nil"
)

//go:embed rdf.ofn
var source string

// Ontology returns the vocabulary's axioms: its declarations, its class and
// property hierarchy, and the labels and definitions its authors wrote.
//
// Each call parses a fresh ontology, so the result is the caller's to add to
// or rewrite. Use [Vocabulary] instead to look terms up without copying.
func Ontology() *owl.Ontology {
	o, err := owl.ParseFunctionalString(source)
	if err != nil {
		panic("rdf: generated ontology does not parse: " + err.Error())
	}
	return o
}

// Vocabulary returns the terms with their labels and definitions, as the
// closed set an untrusted axiom can be validated against. It is built once and
// is safe to share.
func Vocabulary() *owl.Vocabulary { return vocabulary() }

var vocabulary = sync.OnceValue(func() *owl.Vocabulary {
	return owl.NewVocabulary(Ontology(), owl.WithBuiltins())
})
