package main

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
)

// writeRegistry generates vocab/vocab.go, which imports every generated
// package so that a program can go from an IRI or a prefix to the vocabulary
// that defines it without knowing the list in advance.
func writeRegistry(outDir string, srcs []source) error {
	ordered := append([]source(nil), srcs...)
	sort.Slice(ordered, func(i, j int) bool { return ordered[i].pkg < ordered[j].pkg })

	var b bytes.Buffer
	b.WriteString(`// Code generated by cmd/vocabgen. DO NOT EDIT.

// Package vocab is the index of the vocabularies gowl ships.
//
// The subpackages are the vocabularies themselves — one typed constant per
// term, with the axioms their publishers assert. This package exists for the
// things a program cannot hard-code: which vocabulary owns an IRI it just
// read, what a prefix a user typed refers to, or a prefix table covering all
// of them at once.
//
// Importing it links in every vocabulary, schema.org included. Import the one
// subpackage you need when that matters.
package vocab

import (
	"sort"
	"strings"

	"gowl/owl"
`)
	for _, s := range ordered {
		fmt.Fprintf(&b, "\t%q\n", "gowl/vocab/"+s.pkg)
	}
	b.WriteString(")\n\n")

	b.WriteString(`// An Entry is one vocabulary.
type Entry struct {
	// Package is the Go package name, which is also the customary prefix for
	// every vocabulary on this list.
	Package string
	Prefix  string
	// Namespace is the IRI the prefix abbreviates.
	Namespace owl.IRI
	// Title names the vocabulary as its publisher does.
	Title string

	// Ontology returns a fresh copy of the vocabulary's axioms.
	Ontology func() *owl.Ontology
	// Vocabulary returns its terms with labels, built once and shared.
	Vocabulary func() *owl.Vocabulary
}

`)
	b.WriteString("var entries = []Entry{\n")
	for _, s := range ordered {
		fmt.Fprintf(&b, "\t{Package: %q, Prefix: %q, Namespace: %s.Namespace, Title: %q, Ontology: %s.Ontology, Vocabulary: %s.Vocabulary},\n",
			s.pkg, s.prefix, s.pkg, s.title, s.pkg, s.pkg)
	}
	b.WriteString("}\n\n")

	b.WriteString(`// All returns every vocabulary, ordered by package name.
func All() []Entry { return append([]Entry(nil), entries...) }

// ByPrefix returns the vocabulary a prefix names, with or without its trailing
// colon.
func ByPrefix(prefix string) (Entry, bool) {
	prefix = strings.TrimSuffix(prefix, ":")
	for _, e := range entries {
		if e.Prefix == prefix {
			return e, true
		}
	}
	return Entry{}, false
}

// Owner returns the vocabulary that defines an IRI. When namespaces nest, the
// longest match wins.
func Owner(iri owl.IRI) (Entry, bool) {
	best, found := Entry{}, false
	for _, e := range entries {
		if !strings.HasPrefix(string(iri), string(e.Namespace)) || len(iri) == len(e.Namespace) {
			continue
		}
		if !found || len(e.Namespace) > len(best.Namespace) {
			best, found = e, true
		}
	}
	return best, found
}

// Prefixes returns a prefix table covering every vocabulary, on top of the owl,
// rdf, rdfs and xsd prefixes [owl.NewPrefixes] already declares. It is what to
// hand [owl.ParseAxiom] when input may use any of them.
func Prefixes() *owl.Prefixes {
	p := owl.NewPrefixes()
	for _, e := range entries {
		p.Set(e.Prefix, e.Namespace)
	}
	return p
}

// Merge returns one ontology holding the axioms of every vocabulary named,
// with their prefixes declared. It is the starting point for an application
// ontology that reuses standard terms rather than reinventing them.
func Merge(iri owl.IRI, vocabularies ...Entry) *owl.Ontology {
	if len(vocabularies) == 0 {
		vocabularies = entries
	}
	sorted := append([]Entry(nil), vocabularies...)
	sort.Slice(sorted, func(i, j int) bool { return sorted[i].Package < sorted[j].Package })

	out := owl.New(iri)
	seen := map[string]bool{}
	for _, e := range sorted {
		out.Prefix(e.Prefix, e.Namespace)
		src := e.Ontology()
		out.Import(src.IRI)
		for ax := range src.All() {
			if key := owl.CanonicalKey(ax); !seen[key] {
				seen[key] = true
				out.Add(ax)
			}
		}
	}
	return out
}
`)

	src, err := format.Source(b.Bytes())
	if err != nil {
		return err
	}
	return os.WriteFile(filepath.Join(outDir, "vocab.go"), src, 0o644)
}
