// Code generated by cmd/vocabgen. DO NOT EDIT.

// Package prov is the PROV-O provenance ontology as OWL entities.
//
// PROV-O: entities, activities and agents, and the derivation, attribution
// and generation relations between them. The W3C's answer to where a piece
// of data came from.
//
// Each term is a typed constant, so the compiler keeps a class out of a
// property's place. [Ontology] returns the axioms the vocabulary asserts
// about them, and [Vocabulary] the same terms with their labels attached.
//
// Source: https://www.w3.org/ns/prov-o.ttl
// SHA-256: 7d203989f67b38bca572253942acc5a1bf24ce3ccfece16f072dcb4be2b79a96
package prov

import (
	_ "embed"
	"sync"

	"gowl/owl"
)

// Prefix and Namespace are the vocabulary's customary prefix and the IRI it
// abbreviates.
const (
	Prefix            = "prov"
	Namespace owl.IRI = "http://www.w3.org/ns/prov#"
)

// Classes.
const (
	// Activity is prov:Activity.
	Activity owl.Class = "http://www.w3.org/ns/prov#Activity"

	// ActivityInfluence is prov:ActivityInfluence.
	//
	// ActivityInfluence provides additional descriptions of an Activity's
	// binary influence upon any other kind of resource. Instances of
	// ActivityInfluence use the prov:activity property to cite the influencing
	// Activity.
	ActivityInfluence owl.Class = "http://www.w3.org/ns/prov#ActivityInfluence"

	// Agent is prov:Agent.
	Agent owl.Class = "http://www.w3.org/ns/prov#Agent"

	// AgentInfluence is prov:AgentInfluence.
	//
	// AgentInfluence provides additional descriptions of an Agent's binary
	// influence upon any other kind of resource. Instances of AgentInfluence
	// use the prov:agent property to cite the influencing Agent.
	AgentInfluence owl.Class = "http://www.w3.org/ns/prov#AgentInfluence"

	// Association is prov:Association.
	//
	// An instance of prov:Association provides additional descriptions about
	// the binary prov:wasAssociatedWith relation from an prov:Activity to some
	// prov:Agent that had some responsiblity for it. For example, :baking
	// prov:wasAssociatedWith :baker; prov:qualifiedAssociation [ a
	// prov:Association; prov:agent :baker; :foo :bar ].
	Association owl.Class = "http://www.w3.org/ns/prov#Association"

	// Attribution is prov:Attribution.
	//
	// An instance of prov:Attribution provides additional descriptions about
	// the binary prov:wasAttributedTo relation from an prov:Entity to some
	// prov:Agent that had some responsible for it. For example, :cake
	// prov:wasAttributedTo :baker; prov:qualifiedAttribution [ a
	// prov:Attribution; prov:entity :baker; :foo :bar ].
	Attribution owl.Class = "http://www.w3.org/ns/prov#Attribution"

	// Bundle is prov:Bundle.
	//
	// Note that there are kinds of bundles (e.g. handwritten letters, audio
	// recordings, etc.) that are not expressed in PROV-O, but can be still be
	// described by PROV-O.
	Bundle owl.Class = "http://www.w3.org/ns/prov#Bundle"

	// Collection is prov:Collection.
	Collection owl.Class = "http://www.w3.org/ns/prov#Collection"

	// Communication is prov:Communication.
	//
	// An instance of prov:Communication provides additional descriptions about
	// the binary prov:wasInformedBy relation from an informed prov:Activity to
	// the prov:Activity that informed it. For example, :you_jumping_off_bridge
	// prov:wasInformedBy :everyone_else_jumping_off_bridge;
	// prov:qualifiedCommunication [ a prov:Communication; prov:activity
	// :everyone_else_jumping_off_bridge; :foo :bar ].
	Communication owl.Class = "http://www.w3.org/ns/prov#Communication"

	// Delegation is prov:Delegation.
	//
	// An instance of prov:Delegation provides additional descriptions about
	// the binary prov:actedOnBehalfOf relation from a performing prov:Agent to
	// some prov:Agent for whom it was performed. For example, :mixing
	// prov:wasAssociatedWith :toddler . :toddler prov:actedOnBehalfOf :mother;
	// prov:qualifiedDelegation [ a prov:Delegation; prov:entity :mother; :foo
	// :bar ].
	Delegation owl.Class = "http://www.w3.org/ns/prov#Delegation"

	// Derivation is prov:Derivation.
	//
	// An instance of prov:Derivation provides additional descriptions about
	// the binary prov:wasDerivedFrom relation from some derived prov:Entity to
	// another prov:Entity from which it was derived. For example,
	// :chewed_bubble_gum prov:wasDerivedFrom :unwrapped_bubble_gum;
	// prov:qualifiedDerivation [ a prov:Derivation; prov:entity
	// :unwrapped_bubble_gum; :foo :bar ].
	Derivation owl.Class = "http://www.w3.org/ns/prov#Derivation"

	// EmptyCollection is prov:EmptyCollection.
	EmptyCollection owl.Class = "http://www.w3.org/ns/prov#EmptyCollection"

	// End is prov:End.
	//
	// An instance of prov:End provides additional descriptions about the
	// binary prov:wasEndedBy relation from some ended prov:Activity to an
	// prov:Entity that ended it. For example, :ball_game prov:wasEndedBy
	// :buzzer; prov:qualifiedEnd [ a prov:End; prov:entity :buzzer; :foo :bar;
	// prov:atTime '2012-03-09T08:05:08-05:00'^^xsd:dateTime ].
	End owl.Class = "http://www.w3.org/ns/prov#End"

	// Entity is prov:Entity.
	Entity owl.Class = "http://www.w3.org/ns/prov#Entity"

	// EntityInfluence is prov:EntityInfluence.
	//
	// EntityInfluence provides additional descriptions of an Entity's binary
	// influence upon any other kind of resource. Instances of EntityInfluence
	// use the prov:entity property to cite the influencing Entity.
	EntityInfluence owl.Class = "http://www.w3.org/ns/prov#EntityInfluence"

	// Generation is prov:Generation.
	//
	// An instance of prov:Generation provides additional descriptions about
	// the binary prov:wasGeneratedBy relation from a generated prov:Entity to
	// the prov:Activity that generated it. For example, :cake
	// prov:wasGeneratedBy :baking; prov:qualifiedGeneration [ a
	// prov:Generation; prov:activity :baking; :foo :bar ].
	Generation owl.Class = "http://www.w3.org/ns/prov#Generation"

	// Influence is prov:Influence.
	//
	// An instance of prov:Influence provides additional descriptions about the
	// binary prov:wasInfluencedBy relation from some influenced Activity,
	// Entity, or Agent to the influencing Activity, Entity, or Agent. For
	// example, :stomach_ache prov:wasInfluencedBy :spoon;
	// prov:qualifiedInfluence [ a prov:Influence; prov:entity :spoon; :foo
	// :bar ] . Because prov:Influence is a broad relation, the more specific
	// relations (Communication, Delegation, End, etc.) should be used when
	// applicable.
	Influence owl.Class = "http://www.w3.org/ns/prov#Influence"

	// InstantaneousEvent is prov:InstantaneousEvent.
	//
	// An instantaneous event, or event for short, happens in the world and
	// marks a change in the world, in its activities and in its entities. The
	// term 'event' is commonly used in process algebra with a similar meaning.
	// Events represent communications or interactions; they are assumed to be
	// atomic and instantaneous.
	InstantaneousEvent owl.Class = "http://www.w3.org/ns/prov#InstantaneousEvent"

	// Invalidation is prov:Invalidation.
	//
	// An instance of prov:Invalidation provides additional descriptions about
	// the binary prov:wasInvalidatedBy relation from an invalidated
	// prov:Entity to the prov:Activity that invalidated it. For example,
	// :uncracked_egg prov:wasInvalidatedBy :baking; prov:qualifiedInvalidation
	// [ a prov:Invalidation; prov:activity :baking; :foo :bar ].
	Invalidation owl.Class = "http://www.w3.org/ns/prov#Invalidation"

	// Location is prov:Location.
	Location owl.Class = "http://www.w3.org/ns/prov#Location"

	// Organization is prov:Organization.
	Organization owl.Class = "http://www.w3.org/ns/prov#Organization"

	// Person is prov:Person.
	Person owl.Class = "http://www.w3.org/ns/prov#Person"

	// Plan is prov:Plan.
	//
	// There exist no prescriptive requirement on the nature of plans, their
	// representation, the actions or steps they consist of, or their intended
	// goals. Since plans may evolve over time, it may become necessary to
	// track their provenance, so plans themselves are entities. Representing
	// the plan explicitly in the provenance can be useful for various tasks:
	// for example, to validate the execution as represented in the provenance
	// record, to manage expectation failures, or to provide explanations.
	Plan owl.Class = "http://www.w3.org/ns/prov#Plan"

	// PrimarySource is prov:PrimarySource.
	//
	// An instance of prov:PrimarySource provides additional descriptions about
	// the binary prov:hadPrimarySource relation from some secondary
	// prov:Entity to an earlier, primary prov:Entity. For example, :blog
	// prov:hadPrimarySource :newsArticle; prov:qualifiedPrimarySource [ a
	// prov:PrimarySource; prov:entity :newsArticle; :foo :bar ] .
	PrimarySource owl.Class = "http://www.w3.org/ns/prov#PrimarySource"

	// Quotation is prov:Quotation.
	//
	// An instance of prov:Quotation provides additional descriptions about the
	// binary prov:wasQuotedFrom relation from some taken prov:Entity from an
	// earlier, larger prov:Entity. For example, :here_is_looking_at_you_kid
	// prov:wasQuotedFrom :casablanca_script; prov:qualifiedQuotation [ a
	// prov:Quotation; prov:entity :casablanca_script; :foo :bar ].
	Quotation owl.Class = "http://www.w3.org/ns/prov#Quotation"

	// Revision is prov:Revision.
	//
	// An instance of prov:Revision provides additional descriptions about the
	// binary prov:wasRevisionOf relation from some newer prov:Entity to an
	// earlier prov:Entity. For example, :draft_2 prov:wasRevisionOf :draft_1;
	// prov:qualifiedRevision [ a prov:Revision; prov:entity :draft_1; :foo
	// :bar ].
	Revision owl.Class = "http://www.w3.org/ns/prov#Revision"

	// Role is prov:Role.
	Role owl.Class = "http://www.w3.org/ns/prov#Role"

	// SoftwareAgent is prov:SoftwareAgent.
	SoftwareAgent owl.Class = "http://www.w3.org/ns/prov#SoftwareAgent"

	// Start is prov:Start.
	//
	// An instance of prov:Start provides additional descriptions about the
	// binary prov:wasStartedBy relation from some started prov:Activity to an
	// prov:Entity that started it. For example, :foot_race prov:wasStartedBy
	// :bang; prov:qualifiedStart [ a prov:Start; prov:entity :bang; :foo :bar;
	// prov:atTime '2012-03-09T08:05:08-05:00'^^xsd:dateTime ] .
	Start owl.Class = "http://www.w3.org/ns/prov#Start"

	// Usage is prov:Usage.
	//
	// An instance of prov:Usage provides additional descriptions about the
	// binary prov:used relation from some prov:Activity to an prov:Entity that
	// it used. For example, :keynote prov:used :podium; prov:qualifiedUsage [
	// a prov:Usage; prov:entity :podium; :foo :bar ].
	Usage owl.Class = "http://www.w3.org/ns/prov#Usage"
)

// Object properties.
const (
	// ActedOnBehalfOf is prov:actedOnBehalfOf.
	//
	// An object property to express the accountability of an agent towards
	// another agent. The subordinate agent acted on behalf of the responsible
	// agent in an actual activity.
	ActedOnBehalfOf owl.ObjectProperty = "http://www.w3.org/ns/prov#actedOnBehalfOf"

	// ActivityProperty is prov:activity.
	ActivityProperty owl.ObjectProperty = "http://www.w3.org/ns/prov#activity"

	// AgentProperty is prov:agent.
	AgentProperty owl.ObjectProperty = "http://www.w3.org/ns/prov#agent"

	// AlternateOf is prov:alternateOf.
	AlternateOf owl.ObjectProperty = "http://www.w3.org/ns/prov#alternateOf"

	// AtLocation is prov:atLocation.
	//
	// The Location of any resource.
	AtLocation owl.ObjectProperty = "http://www.w3.org/ns/prov#atLocation"

	// EntityProperty is prov:entity.
	EntityProperty owl.ObjectProperty = "http://www.w3.org/ns/prov#entity"

	// Generated is prov:generated.
	Generated owl.ObjectProperty = "http://www.w3.org/ns/prov#generated"

	// HadActivity is prov:hadActivity.
	//
	// The _optional_ Activity of an Influence, which used, generated,
	// invalidated, or was the responsibility of some Entity. This property is
	// _not_ used by ActivityInfluence (use prov:activity instead).
	HadActivity owl.ObjectProperty = "http://www.w3.org/ns/prov#hadActivity"

	// HadGeneration is prov:hadGeneration.
	//
	// The _optional_ Generation involved in an Entity's Derivation.
	HadGeneration owl.ObjectProperty = "http://www.w3.org/ns/prov#hadGeneration"

	// HadMember is prov:hadMember.
	HadMember owl.ObjectProperty = "http://www.w3.org/ns/prov#hadMember"

	// HadPlan is prov:hadPlan.
	//
	// The _optional_ Plan adopted by an Agent in Association with some
	// Activity. Plan specifications are out of the scope of this
	// specification.
	HadPlan owl.ObjectProperty = "http://www.w3.org/ns/prov#hadPlan"

	// HadPrimarySource is prov:hadPrimarySource.
	HadPrimarySource owl.ObjectProperty = "http://www.w3.org/ns/prov#hadPrimarySource"

	// HadRole is prov:hadRole.
	//
	// The _optional_ Role that an Entity assumed in the context of an
	// Activity. For example, :baking prov:used :spoon; prov:qualified [ a
	// prov:Usage; prov:entity :spoon; prov:hadRole roles:mixing_implement ].
	HadRole owl.ObjectProperty = "http://www.w3.org/ns/prov#hadRole"

	// HadUsage is prov:hadUsage.
	//
	// The _optional_ Usage involved in an Entity's Derivation.
	HadUsage owl.ObjectProperty = "http://www.w3.org/ns/prov#hadUsage"

	// Influenced is prov:influenced.
	Influenced owl.ObjectProperty = "http://www.w3.org/ns/prov#influenced"

	// Influencer is prov:influencer.
	//
	// Subproperties of prov:influencer are used to cite the object of an
	// unqualified PROV-O triple whose predicate is a subproperty of
	// prov:wasInfluencedBy (e.g. prov:used, prov:wasGeneratedBy).
	// prov:influencer is used much like rdf:object is used.
	Influencer owl.ObjectProperty = "http://www.w3.org/ns/prov#influencer"

	// Invalidated is prov:invalidated.
	Invalidated owl.ObjectProperty = "http://www.w3.org/ns/prov#invalidated"

	// QualifiedAssociation is prov:qualifiedAssociation.
	//
	// If this Activity prov:wasAssociatedWith Agent :ag, then it can qualify
	// the Association using prov:qualifiedAssociation [ a prov:Association;
	// prov:agent :ag; :foo :bar ].
	QualifiedAssociation owl.ObjectProperty = "http://www.w3.org/ns/prov#qualifiedAssociation"

	// QualifiedAttribution is prov:qualifiedAttribution.
	//
	// If this Entity prov:wasAttributedTo Agent :ag, then it can qualify how
	// it was influenced using prov:qualifiedAttribution [ a prov:Attribution;
	// prov:agent :ag; :foo :bar ].
	QualifiedAttribution owl.ObjectProperty = "http://www.w3.org/ns/prov#qualifiedAttribution"

	// QualifiedCommunication is prov:qualifiedCommunication.
	//
	// If this Activity prov:wasInformedBy Activity :a, then it can qualify how
	// it was influenced using prov:qualifiedCommunication [ a
	// prov:Communication; prov:activity :a; :foo :bar ].
	QualifiedCommunication owl.ObjectProperty = "http://www.w3.org/ns/prov#qualifiedCommunication"

	// QualifiedDelegation is prov:qualifiedDelegation.
	//
	// If this Agent prov:actedOnBehalfOf Agent :ag, then it can qualify how
	// with prov:qualifiedResponsibility [ a prov:Responsibility; prov:agent
	// :ag; :foo :bar ].
	QualifiedDelegation owl.ObjectProperty = "http://www.w3.org/ns/prov#qualifiedDelegation"

	// QualifiedDerivation is prov:qualifiedDerivation.
	//
	// If this Entity prov:wasDerivedFrom Entity :e, then it can qualify how it
	// was derived using prov:qualifiedDerivation [ a prov:Derivation;
	// prov:entity :e; :foo :bar ].
	QualifiedDerivation owl.ObjectProperty = "http://www.w3.org/ns/prov#qualifiedDerivation"

	// QualifiedEnd is prov:qualifiedEnd.
	//
	// If this Activity prov:wasEndedBy Entity :e1, then it can qualify how it
	// was ended using prov:qualifiedEnd [ a prov:End; prov:entity :e1; :foo
	// :bar ].
	QualifiedEnd owl.ObjectProperty = "http://www.w3.org/ns/prov#qualifiedEnd"

	// QualifiedGeneration is prov:qualifiedGeneration.
	//
	// If this Activity prov:generated Entity :e, then it can qualify how it
	// performed the Generation using prov:qualifiedGeneration [ a
	// prov:Generation; prov:entity :e; :foo :bar ].
	QualifiedGeneration owl.ObjectProperty = "http://www.w3.org/ns/prov#qualifiedGeneration"

	// QualifiedInfluence is prov:qualifiedInfluence.
	//
	// Because prov:qualifiedInfluence is a broad relation, the more specific
	// relations (qualifiedCommunication, qualifiedDelegation, qualifiedEnd,
	// etc.) should be used when applicable.
	QualifiedInfluence owl.ObjectProperty = "http://www.w3.org/ns/prov#qualifiedInfluence"

	// QualifiedInvalidation is prov:qualifiedInvalidation.
	//
	// If this Entity prov:wasInvalidatedBy Activity :a, then it can qualify
	// how it was invalidated using prov:qualifiedInvalidation [ a
	// prov:Invalidation; prov:activity :a; :foo :bar ].
	QualifiedInvalidation owl.ObjectProperty = "http://www.w3.org/ns/prov#qualifiedInvalidation"

	// QualifiedPrimarySource is prov:qualifiedPrimarySource.
	//
	// If this Entity prov:hadPrimarySource Entity :e, then it can qualify how
	// using prov:qualifiedPrimarySource [ a prov:PrimarySource; prov:entity
	// :e; :foo :bar ].
	QualifiedPrimarySource owl.ObjectProperty = "http://www.w3.org/ns/prov#qualifiedPrimarySource"

	// QualifiedQuotation is prov:qualifiedQuotation.
	//
	// If this Entity prov:wasQuotedFrom Entity :e, then it can qualify how
	// using prov:qualifiedQuotation [ a prov:Quotation; prov:entity :e; :foo
	// :bar ].
	QualifiedQuotation owl.ObjectProperty = "http://www.w3.org/ns/prov#qualifiedQuotation"

	// QualifiedRevision is prov:qualifiedRevision.
	//
	// If this Entity prov:wasRevisionOf Entity :e, then it can qualify how it
	// was revised using prov:qualifiedRevision [ a prov:Revision; prov:entity
	// :e; :foo :bar ].
	QualifiedRevision owl.ObjectProperty = "http://www.w3.org/ns/prov#qualifiedRevision"

	// QualifiedStart is prov:qualifiedStart.
	//
	// If this Activity prov:wasStartedBy Entity :e1, then it can qualify how
	// it was started using prov:qualifiedStart [ a prov:Start; prov:entity
	// :e1; :foo :bar ].
	QualifiedStart owl.ObjectProperty = "http://www.w3.org/ns/prov#qualifiedStart"

	// QualifiedUsage is prov:qualifiedUsage.
	//
	// If this Activity prov:used Entity :e, then it can qualify how it used it
	// using prov:qualifiedUsage [ a prov:Usage; prov:entity :e; :foo :bar ].
	QualifiedUsage owl.ObjectProperty = "http://www.w3.org/ns/prov#qualifiedUsage"

	// SpecializationOf is prov:specializationOf.
	SpecializationOf owl.ObjectProperty = "http://www.w3.org/ns/prov#specializationOf"

	// Used is prov:used.
	//
	// A prov:Entity that was used by this prov:Activity. For example, :baking
	// prov:used :spoon, :egg, :oven .
	Used owl.ObjectProperty = "http://www.w3.org/ns/prov#used"

	// WasAssociatedWith is prov:wasAssociatedWith.
	//
	// An prov:Agent that had some (unspecified) responsibility for the
	// occurrence of this prov:Activity.
	WasAssociatedWith owl.ObjectProperty = "http://www.w3.org/ns/prov#wasAssociatedWith"

	// WasAttributedTo is prov:wasAttributedTo.
	//
	// Attribution is the ascribing of an entity to an agent.
	WasAttributedTo owl.ObjectProperty = "http://www.w3.org/ns/prov#wasAttributedTo"

	// WasDerivedFrom is prov:wasDerivedFrom.
	//
	// The more specific subproperties of prov:wasDerivedFrom (i.e.,
	// prov:wasQuotedFrom, prov:wasRevisionOf, prov:hadPrimarySource) should be
	// used when applicable.
	WasDerivedFrom owl.ObjectProperty = "http://www.w3.org/ns/prov#wasDerivedFrom"

	// WasEndedBy is prov:wasEndedBy.
	//
	// End is when an activity is deemed to have ended. An end may refer to an
	// entity, known as trigger, that terminated the activity.
	WasEndedBy owl.ObjectProperty = "http://www.w3.org/ns/prov#wasEndedBy"

	// WasGeneratedBy is prov:wasGeneratedBy.
	WasGeneratedBy owl.ObjectProperty = "http://www.w3.org/ns/prov#wasGeneratedBy"

	// WasInfluencedBy is prov:wasInfluencedBy.
	//
	// Because prov:wasInfluencedBy is a broad relation, its more specific
	// subproperties (e.g. prov:wasInformedBy, prov:actedOnBehalfOf,
	// prov:wasEndedBy, etc.) should be used when applicable.
	WasInfluencedBy owl.ObjectProperty = "http://www.w3.org/ns/prov#wasInfluencedBy"

	// WasInformedBy is prov:wasInformedBy.
	//
	// An activity a2 is dependent on or informed by another activity a1, by
	// way of some unspecified entity that is generated by a1 and used by a2.
	WasInformedBy owl.ObjectProperty = "http://www.w3.org/ns/prov#wasInformedBy"

	// WasInvalidatedBy is prov:wasInvalidatedBy.
	WasInvalidatedBy owl.ObjectProperty = "http://www.w3.org/ns/prov#wasInvalidatedBy"

	// WasQuotedFrom is prov:wasQuotedFrom.
	//
	// An entity is derived from an original entity by copying, or 'quoting',
	// some or all of it.
	WasQuotedFrom owl.ObjectProperty = "http://www.w3.org/ns/prov#wasQuotedFrom"

	// WasRevisionOf is prov:wasRevisionOf.
	//
	// A revision is a derivation that revises an entity into a revised
	// version.
	WasRevisionOf owl.ObjectProperty = "http://www.w3.org/ns/prov#wasRevisionOf"

	// WasStartedBy is prov:wasStartedBy.
	//
	// Start is when an activity is deemed to have started. A start may refer
	// to an entity, known as trigger, that initiated the activity.
	WasStartedBy owl.ObjectProperty = "http://www.w3.org/ns/prov#wasStartedBy"
)

// Data properties.
const (
	// AtTime is prov:atTime.
	//
	// The time at which an InstantaneousEvent occurred, in the form of
	// xsd:dateTime.
	AtTime owl.DataProperty = "http://www.w3.org/ns/prov#atTime"

	// EndedAtTime is prov:endedAtTime.
	//
	// The time at which an activity ended. See also prov:startedAtTime.
	EndedAtTime owl.DataProperty = "http://www.w3.org/ns/prov#endedAtTime"

	// GeneratedAtTime is prov:generatedAtTime.
	//
	// The time at which an entity was completely created and is available for
	// use.
	GeneratedAtTime owl.DataProperty = "http://www.w3.org/ns/prov#generatedAtTime"

	// InvalidatedAtTime is prov:invalidatedAtTime.
	//
	// The time at which an entity was invalidated (i.e., no longer usable).
	InvalidatedAtTime owl.DataProperty = "http://www.w3.org/ns/prov#invalidatedAtTime"

	// StartedAtTime is prov:startedAtTime.
	//
	// The time at which an activity started. See also prov:endedAtTime.
	StartedAtTime owl.DataProperty = "http://www.w3.org/ns/prov#startedAtTime"

	// Value is prov:value.
	Value owl.DataProperty = "http://www.w3.org/ns/prov#value"
)

// Annotation properties.
const (
	// Aq is prov:aq.
	Aq owl.AnnotationProperty = "http://www.w3.org/ns/prov#aq"

	// Category is prov:category.
	//
	// Classify prov-o terms into three categories, including 'starting-point',
	// 'qualifed', and 'extended'. This classification is used by the prov-o
	// html document to gently introduce prov-o terms to its users.
	Category owl.AnnotationProperty = "http://www.w3.org/ns/prov#category"

	// Component is prov:component.
	//
	// Classify prov-o terms into six components according to prov-dm,
	// including 'agents-responsibility', 'alternate', 'annotations',
	// 'collections', 'derivations', and 'entities-activities'. This
	// classification is used so that readers of prov-o specification can find
	// its correspondence with the prov-dm specification.
	Component owl.AnnotationProperty = "http://www.w3.org/ns/prov#component"

	// Constraints is prov:constraints.
	//
	// A reference to the principal section of the PROV-CONSTRAINTS document
	// that describes this concept.
	Constraints owl.AnnotationProperty = "http://www.w3.org/ns/prov#constraints"

	// Definition is prov:definition.
	//
	// A definition quoted from PROV-DM or PROV-CONSTRAINTS that describes the
	// concept expressed with this OWL term.
	Definition owl.AnnotationProperty = "http://www.w3.org/ns/prov#definition"

	// Dm is prov:dm.
	//
	// A reference to the principal section of the PROV-DM document that
	// describes this concept.
	Dm owl.AnnotationProperty = "http://www.w3.org/ns/prov#dm"

	// EditorialNote is prov:editorialNote.
	//
	// A note by the OWL development team about how this term expresses the
	// PROV-DM concept, or how it should be used in context of semantic web or
	// linked data.
	EditorialNote owl.AnnotationProperty = "http://www.w3.org/ns/prov#editorialNote"

	// EditorsDefinition is prov:editorsDefinition.
	//
	// When the prov-o term does not have a definition drawn from prov-dm, and
	// the prov-o editor provides one.
	EditorsDefinition owl.AnnotationProperty = "http://www.w3.org/ns/prov#editorsDefinition"

	// Inverse is prov:inverse.
	//
	// PROV-O does not define all property inverses. The directionalities
	// defined in PROV-O should be given preference over those not defined.
	// However, if users wish to name the inverse of a PROV-O property, the
	// local name given by prov:inverse should be used.
	Inverse owl.AnnotationProperty = "http://www.w3.org/ns/prov#inverse"

	// N is prov:n.
	//
	// A reference to the principal section of the PROV-DM document that
	// describes this concept.
	N owl.AnnotationProperty = "http://www.w3.org/ns/prov#n"

	// Order is prov:order.
	//
	// The position that this OWL term should be listed within documentation.
	// The scope of the documentation (e.g., among all terms, among terms
	// within a prov:category, among properties applying to a particular class,
	// etc.) is unspecified.
	Order owl.AnnotationProperty = "http://www.w3.org/ns/prov#order"

	// QualifiedForm is prov:qualifiedForm.
	//
	// This annotation property links a subproperty of prov:wasInfluencedBy
	// with the subclass of prov:Influence and the qualifying property that are
	// used to qualify it. Example annotation: prov:wasGeneratedBy
	// prov:qualifiedForm prov:qualifiedGeneration, prov:Generation . Then this
	// unqualified assertion: :entity1 prov:wasGeneratedBy :activity1 . can be
	// qualified by adding: :entity1 prov:qualifiedGeneration :entity1Gen .
	// :entity1Gen a prov:Generation, prov:Influence; prov:activity :activity1;
	// :customValue 1337 . Note how the value of the unqualified influence
	// (prov:wasGeneratedBy :activity1) is mirrored as the value of the
	// prov:activity (or prov:entity, or prov:agent) property on the influence
	// class.
	QualifiedForm owl.AnnotationProperty = "http://www.w3.org/ns/prov#qualifiedForm"

	// SharesDefinitionWith is prov:sharesDefinitionWith.
	SharesDefinitionWith owl.AnnotationProperty = "http://www.w3.org/ns/prov#sharesDefinitionWith"

	// SpecializationOfAnnotation is prov:specializationOf.
	SpecializationOfAnnotation owl.AnnotationProperty = "http://www.w3.org/ns/prov#specializationOf"

	// Todo is prov:todo.
	Todo owl.AnnotationProperty = "http://www.w3.org/ns/prov#todo"

	// UnqualifiedForm is prov:unqualifiedForm.
	//
	// Classes and properties used to qualify relationships are annotated with
	// prov:unqualifiedForm to indicate the property used to assert an
	// unqualified provenance relation.
	UnqualifiedForm owl.AnnotationProperty = "http://www.w3.org/ns/prov#unqualifiedForm"

	// WasRevisionOfAnnotation is prov:wasRevisionOf.
	//
	// A revision is a derivation that revises an entity into a revised
	// version.
	WasRevisionOfAnnotation owl.AnnotationProperty = "http://www.w3.org/ns/prov#wasRevisionOf"
)

//go:embed prov.ofn
var source string

// Ontology returns the vocabulary's axioms: its declarations, its class and
// property hierarchy, and the labels and definitions its authors wrote.
//
// Each call parses a fresh ontology, so the result is the caller's to add to
// or rewrite. Use [Vocabulary] instead to look terms up without copying.
func Ontology() *owl.Ontology {
	o, err := owl.ParseFunctionalString(source)
	if err != nil {
		panic("prov: generated ontology does not parse: " + err.Error())
	}
	return o
}

// Vocabulary returns the terms with their labels and definitions, as the
// closed set an untrusted axiom can be validated against. It is built once and
// is safe to share.
func Vocabulary() *owl.Vocabulary { return vocabulary() }

var vocabulary = sync.OnceValue(func() *owl.Vocabulary {
	return owl.NewVocabulary(Ontology())
})
