// Code generated by cmd/vocabgen. DO NOT EDIT.

// Package dc is the Dublin Core Metadata Element Set as OWL entities.
//
// The original fifteen Dublin Core elements. They are superseded by the
// dcterms package for new work, and are here because a great deal of
// published data still uses them.
//
// Each term is a typed constant, so the compiler keeps a class out of a
// property's place. [Ontology] returns the axioms the vocabulary asserts
// about them, and [Vocabulary] the same terms with their labels attached.
//
// Source: https://www.dublincore.org/specifications/dublin-core/dcmi-terms/dublin_core_elements.ttl
// SHA-256: ffb46b7a21e40344b93bc4ad2e6808b24dd53e261995ec3a926df6bcd87bbfa5
package dc

import (
	_ "embed"
	"sync"

	"gowl/owl"
)

// Prefix and Namespace are the vocabulary's customary prefix and the IRI it
// abbreviates.
const (
	Prefix            = "dc"
	Namespace owl.IRI = "http://purl.org/dc/elements/1.1/"
)

// Object properties.
const (
	// Contributor is dc:contributor.
	//
	// An entity responsible for making contributions to the resource.
	Contributor owl.ObjectProperty = "http://purl.org/dc/elements/1.1/contributor"

	// Coverage is dc:coverage.
	//
	// The spatial or temporal topic of the resource, spatial applicability of
	// the resource, or jurisdiction under which the resource is relevant.
	Coverage owl.ObjectProperty = "http://purl.org/dc/elements/1.1/coverage"

	// Creator is dc:creator.
	//
	// An entity primarily responsible for making the resource.
	Creator owl.ObjectProperty = "http://purl.org/dc/elements/1.1/creator"

	// Date is dc:date.
	//
	// A point or period of time associated with an event in the lifecycle of
	// the resource.
	Date owl.ObjectProperty = "http://purl.org/dc/elements/1.1/date"

	// Description is dc:description.
	//
	// An account of the resource.
	Description owl.ObjectProperty = "http://purl.org/dc/elements/1.1/description"

	// Format is dc:format.
	//
	// The file format, physical medium, or dimensions of the resource.
	Format owl.ObjectProperty = "http://purl.org/dc/elements/1.1/format"

	// Identifier is dc:identifier.
	//
	// An unambiguous reference to the resource within a given context.
	Identifier owl.ObjectProperty = "http://purl.org/dc/elements/1.1/identifier"

	// Language is dc:language.
	//
	// A language of the resource.
	Language owl.ObjectProperty = "http://purl.org/dc/elements/1.1/language"

	// Publisher is dc:publisher.
	//
	// An entity responsible for making the resource available.
	Publisher owl.ObjectProperty = "http://purl.org/dc/elements/1.1/publisher"

	// Relation is dc:relation.
	//
	// A related resource.
	Relation owl.ObjectProperty = "http://purl.org/dc/elements/1.1/relation"

	// Rights is dc:rights.
	//
	// Information about rights held in and over the resource.
	Rights owl.ObjectProperty = "http://purl.org/dc/elements/1.1/rights"

	// Source is dc:source.
	//
	// A related resource from which the described resource is derived.
	Source owl.ObjectProperty = "http://purl.org/dc/elements/1.1/source"

	// Subject is dc:subject.
	//
	// The topic of the resource.
	Subject owl.ObjectProperty = "http://purl.org/dc/elements/1.1/subject"

	// Title is dc:title.
	//
	// A name given to the resource.
	Title owl.ObjectProperty = "http://purl.org/dc/elements/1.1/title"

	// Type is dc:type.
	//
	// The nature or genre of the resource.
	Type owl.ObjectProperty = "http://purl.org/dc/elements/1.1/type"
)

//go:embed dc.ofn
var source string

// Ontology returns the vocabulary's axioms: its declarations, its class and
// property hierarchy, and the labels and definitions its authors wrote.
//
// Each call parses a fresh ontology, so the result is the caller's to add to
// or rewrite. Use [Vocabulary] instead to look terms up without copying.
func Ontology() *owl.Ontology {
	o, err := owl.ParseFunctionalString(source)
	if err != nil {
		panic("dc: generated ontology does not parse: " + err.Error())
	}
	return o
}

// Vocabulary returns the terms with their labels and definitions, as the
// closed set an untrusted axiom can be validated against. It is built once and
// is safe to share.
func Vocabulary() *owl.Vocabulary { return vocabulary() }

var vocabulary = sync.OnceValue(func() *owl.Vocabulary {
	return owl.NewVocabulary(Ontology())
})
