// Package vocabgen writes a Go package for one published vocabulary.
//
// A generated package holds two files: a functional-syntax rendering of the
// ontology, and Go source with one typed constant per term. The axioms live in
// the .ofn file rather than in Go statements because that keeps the diff of a
// regenerated vocabulary readable, and because parsing it back is the same
// code path any other gowl user takes.
package vocabgen

import (
	"bytes"
	"fmt"
	"go/format"
	"html"
	"strings"
	"unicode"

	"gowl/owl"
)

// A Package is one vocabulary to generate.
type Package struct {
	// Name is the Go package name, e.g. "skos".
	Name string
	// Title is the vocabulary's own name, e.g. "SKOS Vocabulary".
	Title string
	// Summary is a sentence for the package doc comment.
	Summary string
	// SourceURL is where the document was fetched from.
	SourceURL string
	// SourceSHA256 pins the document that was read.
	SourceSHA256 string
	// Namespaces are the IRI prefixes whose terms get a constant.
	Namespaces []string
	// Prefix is the vocabulary's customary prefix, e.g. "skos".
	Prefix string
	// Namespace is the vocabulary's main namespace IRI.
	Namespace string

	Ontology *owl.Ontology
}

// Files is what a generation produced.
type Files struct {
	Go  []byte
	OFN []byte
	// Terms is the number of constants written.
	Terms int
}

// Generate renders the package.
func Generate(p Package) (*Files, error) {
	terms := p.terms()
	names := assignNames(terms)

	var b bytes.Buffer
	p.writeHeader(&b)
	p.writeConstants(&b, terms, names)
	p.writeAccessors(&b)

	src, err := format.Source(b.Bytes())
	if err != nil {
		return nil, fmt.Errorf("vocabgen: %s: %w", p.Name, err)
	}
	return &Files{Go: src, OFN: []byte(p.Ontology.Functional()), Terms: len(terms)}, nil
}

// terms returns the entities that get a constant: everything in the
// vocabulary's own namespaces, in signature order. Ownership is the only test
// — the RDF and RDFS packages consist entirely of terms owl.IsBuiltin reports
// as built in, and those are exactly the terms they exist to name.
func (p Package) terms() []owl.Entity {
	var out []owl.Entity
	for _, e := range p.Ontology.Signature() {
		if !p.owns(string(e.IRI())) {
			continue
		}
		out = append(out, e)
	}
	return out
}

func (p Package) owns(iri string) bool {
	for _, ns := range p.Namespaces {
		if strings.HasPrefix(iri, ns) && len(iri) > len(ns) {
			return true
		}
	}
	return false
}

func (p Package) writeHeader(b *bytes.Buffer) {
	fmt.Fprintf(b, "// Code generated by cmd/vocabgen. DO NOT EDIT.\n\n")

	title := p.Title
	if title == "" {
		title = p.Name
	}
	fmt.Fprintf(b, "// Package %s is the %s as OWL entities.\n//\n", p.Name, title)
	if p.Summary != "" {
		for _, line := range wrap(p.Summary, 72) {
			fmt.Fprintf(b, "// %s\n", line)
		}
		fmt.Fprintf(b, "//\n")
	}
	fmt.Fprintf(b, "// Each term is a typed constant, so the compiler keeps a class out of a\n")
	fmt.Fprintf(b, "// property's place. [Ontology] returns the axioms the vocabulary asserts\n")
	fmt.Fprintf(b, "// about them, and [Vocabulary] the same terms with their labels attached.\n")
	fmt.Fprintf(b, "//\n")
	fmt.Fprintf(b, "// Source: %s\n", p.SourceURL)
	fmt.Fprintf(b, "// SHA-256: %s\n", p.SourceSHA256)
	fmt.Fprintf(b, "package %s\n\n", p.Name)
	fmt.Fprintf(b, "import (\n\t_ \"embed\"\n\t\"sync\"\n\n\t\"gowl/owl\"\n)\n\n")

	fmt.Fprintf(b, "// Prefix and Namespace are the vocabulary's customary prefix and the IRI it\n")
	fmt.Fprintf(b, "// abbreviates.\nconst (\n")
	fmt.Fprintf(b, "\tPrefix = %q\n", p.Prefix)
	fmt.Fprintf(b, "\tNamespace owl.IRI = %q\n)\n\n", p.Namespace)
}

var kindGroups = []struct {
	kind    owl.Kind
	heading string
	goType  string
}{
	{owl.KindClass, "Classes", "owl.Class"},
	{owl.KindDatatype, "Datatypes", "owl.Datatype"},
	{owl.KindObjectProperty, "Object properties", "owl.ObjectProperty"},
	{owl.KindDataProperty, "Data properties", "owl.DataProperty"},
	{owl.KindAnnotationProperty, "Annotation properties", "owl.AnnotationProperty"},
	{owl.KindNamedIndividual, "Individuals", "owl.NamedIndividual"},
}

func (p Package) writeConstants(b *bytes.Buffer, terms []owl.Entity, names map[owl.Entity]string) {
	index := p.Ontology.Index()
	comments := comments(p.Ontology)

	for _, group := range kindGroups {
		var inGroup []owl.Entity
		for _, e := range terms {
			if e.Kind() == group.kind {
				inGroup = append(inGroup, e)
			}
		}
		if len(inGroup) == 0 {
			continue
		}
		fmt.Fprintf(b, "// %s.\nconst (\n", group.heading)
		for i, e := range inGroup {
			if i > 0 {
				b.WriteString("\n")
			}
			p.writeDoc(b, names[e], e, index.Label(e), comments[e.IRI()])
			fmt.Fprintf(b, "\t%s %s = %q\n", names[e], group.goType, string(e.IRI()))
		}
		fmt.Fprintf(b, ")\n\n")
	}
}

// writeDoc writes a constant's comment: its compact name first, so the IRI is
// always visible, then the vocabulary's own label and definition.
//
// The definition is reduced to plain text on the way, because schema.org
// writes its comments in HTML and a Go doc comment is not the place for a
// link tag. The .ofn file keeps what the publisher wrote, untouched.
func (p Package) writeDoc(b *bytes.Buffer, name string, e owl.Entity, label, comment string) {
	compact := p.compact(e.IRI())
	head := fmt.Sprintf("%s is %s", name, compact)
	if label = plain(label); label != "" && !strings.EqualFold(label, strings.TrimPrefix(compact, p.Prefix+":")) {
		head += fmt.Sprintf(", %q", label)
	}
	head += "."
	for _, line := range wrap(head, 72) {
		fmt.Fprintf(b, "\t// %s\n", line)
	}
	if comment = plain(comment); comment != "" {
		fmt.Fprintf(b, "\t//\n")
		for _, line := range wrap(comment, 72) {
			fmt.Fprintf(b, "\t// %s\n", line)
		}
	}
}

// plain reduces a publisher's prose to one line of text: markup dropped,
// entities resolved, whitespace collapsed.
func plain(s string) string {
	var b strings.Builder
	depth := 0
	for _, r := range s {
		switch {
		case r == '<':
			depth++
			b.WriteByte(' ')
		case r == '>' && depth > 0:
			depth--
		case depth == 0:
			b.WriteRune(r)
		}
	}
	return oneLine(html.UnescapeString(b.String()))
}

func (p Package) compact(iri owl.IRI) string {
	if strings.HasPrefix(string(iri), p.Namespace) {
		return p.Prefix + ":" + string(iri)[len(p.Namespace):]
	}
	if c, ok := p.Ontology.Prefixes.Compact(iri); ok {
		return c
	}
	return "<" + string(iri) + ">"
}

// builtinNamespaces are the vocabularies owl.IsBuiltin reports as built in,
// and which owl.NewVocabulary therefore leaves out by default.
var builtinNamespaces = []string{
	string(owl.NamespaceOWL), string(owl.NamespaceRDF),
	string(owl.NamespaceRDFS), string(owl.NamespaceXSD),
}

// vocabularyOptions is the argument list for the generated NewVocabulary call.
//
// DeclaredOnly is always passed: a vocabulary document references terms it does
// not define — FOAF states that foaf:Person is equivalent to schema.org's
// Person — and those have no business in the closed set of what this
// vocabulary offers. Only the terms it declares are its own.
//
// A package whose own terms are OWL's built-in ones also has to ask for them,
// or its Vocabulary would come back empty.
func (p Package) vocabularyOptions() string {
	opts := ", owl.DeclaredOnly()"
	for _, ns := range builtinNamespaces {
		if p.Namespace == ns {
			return opts + ", owl.WithBuiltins()"
		}
	}
	return opts
}

func (p Package) writeAccessors(b *bytes.Buffer) {
	fmt.Fprintf(b, `//go:embed %s.ofn
var source string

// Ontology returns the vocabulary's axioms: its declarations, its class and
// property hierarchy, and the labels and definitions its authors wrote.
//
// Each call parses a fresh ontology, so the result is the caller's to add to
// or rewrite. Use [Vocabulary] instead to look terms up without copying.
func Ontology() *owl.Ontology {
	o, err := owl.ParseFunctionalString(source)
	if err != nil {
		panic("%s: generated ontology does not parse: " + err.Error())
	}
	return o
}

// Vocabulary returns the terms this vocabulary declares, with their labels and
// definitions, as the closed set an untrusted axiom can be validated against.
// Terms it only references — another vocabulary's, named to relate the two —
// are not part of it. It is built once and is safe to share.
func Vocabulary() *owl.Vocabulary { return vocabulary() }

var vocabulary = sync.OnceValue(func() *owl.Vocabulary {
	return owl.NewVocabulary(Ontology()%s)
})
`, p.Name, p.Name, p.vocabularyOptions())
}

// --- naming -----------------------------------------------------------------

// assignNames gives every term a unique Go identifier. Terms are visited in
// signature order, so the assignment does not move when a vocabulary gains a
// term. A name already taken — by another kind's term, or by the package's own
// API — gains its entity kind as a suffix.
func assignNames(terms []owl.Entity) map[owl.Entity]string {
	taken := map[string]bool{
		"Prefix": true, "Namespace": true, "Ontology": true,
		"Vocabulary": true, "source": true, "vocabulary": true,
	}
	names := make(map[owl.Entity]string, len(terms))
	for _, e := range terms {
		base := identifier(localName(string(e.IRI())))
		name := base
		if taken[name] {
			name = base + kindSuffix(e.Kind())
		}
		for i := 2; taken[name]; i++ {
			name = fmt.Sprintf("%s%s%d", base, kindSuffix(e.Kind()), i)
		}
		taken[name] = true
		names[e] = name
	}
	return names
}

func kindSuffix(k owl.Kind) string {
	switch k {
	case owl.KindClass:
		return "Class"
	case owl.KindDatatype:
		return "Datatype"
	case owl.KindObjectProperty:
		return "Property"
	case owl.KindDataProperty:
		return "DataProperty"
	case owl.KindAnnotationProperty:
		return "Annotation"
	default:
		return "Individual"
	}
}

// localName is the part of an IRI after the last separator.
func localName(iri string) string {
	if i := strings.LastIndexAny(iri, "#/:"); i >= 0 {
		return iri[i+1:]
	}
	return iri
}

// identifier turns a local name into an exported Go identifier, keeping the
// original's internal capitalisation so that isPrimaryTopicOf stays readable
// as IsPrimaryTopicOf.
func identifier(local string) string {
	var b strings.Builder
	upper := true
	for _, r := range local {
		switch {
		case r == '_' || r == '-' || r == '.' || r == ' ':
			upper = true
		case unicode.IsLetter(r) || unicode.IsDigit(r):
			if upper {
				b.WriteRune(unicode.ToUpper(r))
				upper = false
			} else {
				b.WriteRune(r)
			}
		}
	}
	s := b.String()
	if s == "" {
		return "Term"
	}
	if unicode.IsDigit(rune(s[0])) {
		return "N" + s
	}
	return s
}

// --- text -------------------------------------------------------------------

// comments collects the first rdfs:comment or skos:definition asserted for
// each term, which is where these vocabularies put their prose.
func comments(o *owl.Ontology) map[owl.IRI]string {
	const skosDefinition = owl.AnnotationProperty("http://www.w3.org/2004/02/skos/core#definition")
	out := map[owl.IRI]string{}
	prefer := map[owl.IRI]bool{}
	for ax := range o.All() {
		a, ok := owl.Unwrap(ax).(owl.AnnotationAssertion)
		if !ok {
			continue
		}
		l, isLiteral := a.Value.(owl.Literal)
		if !isLiteral || l.Value == "" {
			continue
		}
		switch a.Property {
		case owl.RDFSComment:
			if !prefer[a.Subject] {
				out[a.Subject], prefer[a.Subject] = l.Value, true
			}
		case skosDefinition:
			if _, seen := out[a.Subject]; !seen {
				out[a.Subject] = l.Value
			}
		}
	}
	return out
}

func oneLine(s string) string { return strings.Join(strings.Fields(s), " ") }

// wrap breaks text into lines of at most width characters, never splitting a
// word.
func wrap(s string, width int) []string {
	words := strings.Fields(s)
	if len(words) == 0 {
		return nil
	}
	var out []string
	line := words[0]
	for _, w := range words[1:] {
		if len(line)+1+len(w) > width {
			out = append(out, line)
			line = w
			continue
		}
		line += " " + w
	}
	return append(out, line)
}
