// Code generated by cmd/vocabgen. DO NOT EDIT.

// Package skosxl is the SKOS eXtension for Labels as OWL entities.
//
// SKOS-XL, which turns a label into a resource of its own so that labels
// can carry their own provenance and relationships.
//
// Each term is a typed constant, so the compiler keeps a class out of a
// property's place. [Ontology] returns the axioms the vocabulary asserts
// about them, and [Vocabulary] the same terms with their labels attached.
//
// Source: https://www.w3.org/2008/05/skos-xl.rdf
// SHA-256: fb6519c5719250d77f17a84ac28c75660c7de09da7286dda138bbe9d8f834b9a
package skosxl

import (
	_ "embed"
	"sync"

	"gowl/owl"
)

// Prefix and Namespace are the vocabulary's customary prefix and the IRI it
// abbreviates.
const (
	Prefix            = "skosxl"
	Namespace owl.IRI = "http://www.w3.org/2008/05/skos-xl#"
)

// Classes.
const (
	// Label is skosxl:Label.
	//
	// A special class of lexical entities.
	Label owl.Class = "http://www.w3.org/2008/05/skos-xl#Label"
)

// Object properties.
const (
	// AltLabel is skosxl:altLabel, "alternative label".
	//
	// If C skosxl:altLabel L and L skosxl:literalForm V, then X skos:altLabel
	// V.
	AltLabel owl.ObjectProperty = "http://www.w3.org/2008/05/skos-xl#altLabel"

	// HiddenLabel is skosxl:hiddenLabel, "hidden label".
	//
	// If C skosxl:hiddenLabel L and L skosxl:literalForm V, then C
	// skos:hiddenLabel V.
	HiddenLabel owl.ObjectProperty = "http://www.w3.org/2008/05/skos-xl#hiddenLabel"

	// LabelRelation is skosxl:labelRelation, "label relation".
	//
	// The property skosxl:labelRelation is used for representing binary
	// ('direct') relations between instances of the class skosxl:Label.
	LabelRelation owl.ObjectProperty = "http://www.w3.org/2008/05/skos-xl#labelRelation"

	// PrefLabel is skosxl:prefLabel, "preferred label".
	//
	// If C skosxl:prefLabel L and L skosxl:literalForm V, then X
	// skos:prefLabel V.
	PrefLabel owl.ObjectProperty = "http://www.w3.org/2008/05/skos-xl#prefLabel"
)

// Data properties.
const (
	// LiteralForm is skosxl:literalForm, "literal form".
	//
	// If two instances of the class skosxl:Label have the same literal form,
	// they are not necessarily the same resource.
	LiteralForm owl.DataProperty = "http://www.w3.org/2008/05/skos-xl#literalForm"
)

//go:embed skosxl.ofn
var source string

// Ontology returns the vocabulary's axioms: its declarations, its class and
// property hierarchy, and the labels and definitions its authors wrote.
//
// Each call parses a fresh ontology, so the result is the caller's to add to
// or rewrite. Use [Vocabulary] instead to look terms up without copying.
func Ontology() *owl.Ontology {
	o, err := owl.ParseFunctionalString(source)
	if err != nil {
		panic("skosxl: generated ontology does not parse: " + err.Error())
	}
	return o
}

// Vocabulary returns the terms with their labels and definitions, as the
// closed set an untrusted axiom can be validated against. It is built once and
// is safe to share.
func Vocabulary() *owl.Vocabulary { return vocabulary() }

var vocabulary = sync.OnceValue(func() *owl.Vocabulary {
	return owl.NewVocabulary(Ontology())
})
