// Code generated by cmd/vocabgen. DO NOT EDIT.

// Package vocab is the index of the vocabularies gowl ships.
//
// The subpackages are the vocabularies themselves — one typed constant per
// term, with the axioms their publishers assert. This package exists for the
// things a program cannot hard-code: which vocabulary owns an IRI it just
// read, what a prefix a user typed refers to, or a prefix table covering all
// of them at once.
//
// Importing it links in every vocabulary, schema.org included. Import the one
// subpackage you need when that matters.
package vocab

import (
	"sort"
	"strings"

	"gowl/owl"
	"gowl/vocab/dc"
	"gowl/vocab/dcat"
	"gowl/vocab/dcterms"
	"gowl/vocab/foaf"
	"gowl/vocab/org"
	"gowl/vocab/prov"
	"gowl/vocab/rdf"
	"gowl/vocab/rdfs"
	"gowl/vocab/schema"
	"gowl/vocab/skos"
	"gowl/vocab/skosxl"
	"gowl/vocab/time"
)

// An Entry is one vocabulary.
type Entry struct {
	// Package is the Go package name, which is also the customary prefix for
	// every vocabulary on this list.
	Package string
	Prefix  string
	// Namespace is the IRI the prefix abbreviates.
	Namespace owl.IRI
	// Title names the vocabulary as its publisher does.
	Title string

	// Ontology returns a fresh copy of the vocabulary's axioms.
	Ontology func() *owl.Ontology
	// Vocabulary returns its terms with labels, built once and shared.
	Vocabulary func() *owl.Vocabulary
}

var entries = []Entry{
	{Package: "dc", Prefix: "dc", Namespace: dc.Namespace, Title: "Dublin Core Metadata Element Set", Ontology: dc.Ontology, Vocabulary: dc.Vocabulary},
	{Package: "dcat", Prefix: "dcat", Namespace: dcat.Namespace, Title: "Data Catalog Vocabulary", Ontology: dcat.Ontology, Vocabulary: dcat.Vocabulary},
	{Package: "dcterms", Prefix: "dcterms", Namespace: dcterms.Namespace, Title: "DCMI Metadata Terms", Ontology: dcterms.Ontology, Vocabulary: dcterms.Vocabulary},
	{Package: "foaf", Prefix: "foaf", Namespace: foaf.Namespace, Title: "FOAF vocabulary", Ontology: foaf.Ontology, Vocabulary: foaf.Vocabulary},
	{Package: "org", Prefix: "org", Namespace: org.Namespace, Title: "Organization Ontology", Ontology: org.Ontology, Vocabulary: org.Vocabulary},
	{Package: "prov", Prefix: "prov", Namespace: prov.Namespace, Title: "PROV-O provenance ontology", Ontology: prov.Ontology, Vocabulary: prov.Vocabulary},
	{Package: "rdf", Prefix: "rdf", Namespace: rdf.Namespace, Title: "RDF vocabulary", Ontology: rdf.Ontology, Vocabulary: rdf.Vocabulary},
	{Package: "rdfs", Prefix: "rdfs", Namespace: rdfs.Namespace, Title: "RDF Schema vocabulary", Ontology: rdfs.Ontology, Vocabulary: rdfs.Vocabulary},
	{Package: "schema", Prefix: "schema", Namespace: schema.Namespace, Title: "Schema.org vocabulary", Ontology: schema.Ontology, Vocabulary: schema.Vocabulary},
	{Package: "skos", Prefix: "skos", Namespace: skos.Namespace, Title: "SKOS Core vocabulary", Ontology: skos.Ontology, Vocabulary: skos.Vocabulary},
	{Package: "skosxl", Prefix: "skosxl", Namespace: skosxl.Namespace, Title: "SKOS eXtension for Labels", Ontology: skosxl.Ontology, Vocabulary: skosxl.Vocabulary},
	{Package: "time", Prefix: "time", Namespace: time.Namespace, Title: "OWL-Time ontology", Ontology: time.Ontology, Vocabulary: time.Vocabulary},
}

// All returns every vocabulary, ordered by package name.
func All() []Entry { return append([]Entry(nil), entries...) }

// ByPrefix returns the vocabulary a prefix names, with or without its trailing
// colon.
func ByPrefix(prefix string) (Entry, bool) {
	prefix = strings.TrimSuffix(prefix, ":")
	for _, e := range entries {
		if e.Prefix == prefix {
			return e, true
		}
	}
	return Entry{}, false
}

// Owner returns the vocabulary that defines an IRI. When namespaces nest, the
// longest match wins.
func Owner(iri owl.IRI) (Entry, bool) {
	best, found := Entry{}, false
	for _, e := range entries {
		if !strings.HasPrefix(string(iri), string(e.Namespace)) || len(iri) == len(e.Namespace) {
			continue
		}
		if !found || len(e.Namespace) > len(best.Namespace) {
			best, found = e, true
		}
	}
	return best, found
}

// Prefixes returns a prefix table covering every vocabulary, on top of the owl,
// rdf, rdfs and xsd prefixes [owl.NewPrefixes] already declares. It is what to
// hand [owl.ParseAxiom] when input may use any of them.
func Prefixes() *owl.Prefixes {
	p := owl.NewPrefixes()
	for _, e := range entries {
		p.Set(e.Prefix, e.Namespace)
	}
	return p
}

// Merge returns one ontology holding the axioms of every vocabulary named,
// with their prefixes declared. It is the starting point for an application
// ontology that reuses standard terms rather than reinventing them.
func Merge(iri owl.IRI, vocabularies ...Entry) *owl.Ontology {
	if len(vocabularies) == 0 {
		vocabularies = entries
	}
	sorted := append([]Entry(nil), vocabularies...)
	sort.Slice(sorted, func(i, j int) bool { return sorted[i].Package < sorted[j].Package })

	out := owl.New(iri)
	seen := map[string]bool{}
	for _, e := range sorted {
		out.Prefix(e.Prefix, e.Namespace)
		src := e.Ontology()
		out.Import(src.IRI)
		for ax := range src.All() {
			if key := owl.CanonicalKey(ax); !seen[key] {
				seen[key] = true
				out.Add(ax)
			}
		}
	}
	return out
}
