// Code generated by cmd/vocabgen. DO NOT EDIT.

// Package dcat is the Data Catalog Vocabulary as OWL entities.
//
// DCAT: catalogs, datasets, distributions and data services. The
// interchange format for open data portals, and the base of national
// profiles such as DCAT-AP.
//
// Each term is a typed constant, so the compiler keeps a class out of a
// property's place. [Ontology] returns the axioms the vocabulary asserts
// about them, and [Vocabulary] the same terms with their labels attached.
//
// Source: https://www.w3.org/ns/dcat.ttl
// SHA-256: d1624d3bbf364f6fc1d43b9a188bbb9e67639b1a7d46a5cb7ea3f5d47d02b62f
package dcat

import (
	_ "embed"
	"sync"

	"gowl/owl"
)

// Prefix and Namespace are the vocabulary's customary prefix and the IRI it
// abbreviates.
const (
	Prefix            = "dcat"
	Namespace owl.IRI = "http://www.w3.org/ns/dcat#"
)

// Classes.
const (
	// Catalog is dcat:Catalog.
	//
	// A curated collection of metadata about resources (e.g., datasets and
	// data services in the context of a data catalog).
	Catalog owl.Class = "http://www.w3.org/ns/dcat#Catalog"

	// CatalogRecord is dcat:CatalogRecord, "Catalog Record".
	//
	// 1つのデータセットを記述したデータ・カタログ内のレコード。
	CatalogRecord owl.Class = "http://www.w3.org/ns/dcat#CatalogRecord"

	// DataService is dcat:DataService, "Data service".
	//
	// A site or end-point providing operations related to the discovery of,
	// access to, or processing functions on, data or related resources.
	DataService owl.Class = "http://www.w3.org/ns/dcat#DataService"

	// Dataset is dcat:Dataset, "Conjunto de datos".
	//
	// 1つのエージェントによって公開またはキュレートされ、1つ以上の形式でアクセスまたはダウンロードできるデータの集合。
	Dataset owl.Class = "http://www.w3.org/ns/dcat#Dataset"

	// DatasetSeries is dcat:DatasetSeries, "Dataset series".
	//
	// A collection of datasets that are published separately, but share some
	// characteristics that group them.
	DatasetSeries owl.Class = "http://www.w3.org/ns/dcat#DatasetSeries"

	// Distribution is dcat:Distribution, "Distribuce".
	//
	// A specific representation of a dataset. A dataset might be available in
	// multiple serializations that may differ in various ways, including
	// natural language, media-type or format, schematic organization, temporal
	// and spatial resolution, level of detail or profiles (which might specify
	// any or all of the above).
	Distribution owl.Class = "http://www.w3.org/ns/dcat#Distribution"

	// Relationship is dcat:Relationship, "Relación".
	//
	// An association class for attaching additional information to a
	// relationship between DCAT Resources.
	Relationship owl.Class = "http://www.w3.org/ns/dcat#Relationship"

	// Resource is dcat:Resource, "Catalogued resource".
	//
	// Recurso publicado o curado por un agente único.
	Resource owl.Class = "http://www.w3.org/ns/dcat#Resource"

	// Role is dcat:Role, "Rol".
	//
	// A role is the function of a resource or agent with respect to another
	// resource, in the context of resource attribution or resource
	// relationships.
	Role owl.Class = "http://www.w3.org/ns/dcat#Role"
)

// Object properties.
const (
	// AccessService is dcat:accessService, "data access service".
	//
	// A site or end-point that gives access to the distribution of the
	// dataset.
	AccessService owl.ObjectProperty = "http://www.w3.org/ns/dcat#accessService"

	// AccessURL is dcat:accessURL, "URL d'accès".
	//
	// A URL of a resource that gives access to a distribution of the dataset.
	// E.g. landing page, feed, SPARQL endpoint. Use for all cases except a
	// simple download link, in which case downloadURL is preferred.
	AccessURL owl.ObjectProperty = "http://www.w3.org/ns/dcat#accessURL"

	// CatalogProperty is dcat:catalog.
	//
	// A catalog that is listed in the catalog.
	CatalogProperty owl.ObjectProperty = "http://www.w3.org/ns/dcat#catalog"

	// CompressFormat is dcat:compressFormat, "compression format".
	//
	// El formato de la distribución en el que los datos están en forma
	// comprimida, e.g. para reducir el tamaño del archivo a bajar.
	CompressFormat owl.ObjectProperty = "http://www.w3.org/ns/dcat#compressFormat"

	// ContactPoint is dcat:contactPoint, "Punto de contacto".
	//
	// Información relevante de contacto para el recurso catalogado. Se
	// recomienda el uso de vCard.
	ContactPoint owl.ObjectProperty = "http://www.w3.org/ns/dcat#contactPoint"

	// DatasetProperty is dcat:dataset, "conjunto de datos".
	//
	// A dataset that is listed in the catalog.
	DatasetProperty owl.ObjectProperty = "http://www.w3.org/ns/dcat#dataset"

	// DistributionProperty is dcat:distribution, "distribuce".
	//
	// An available distribution of the dataset.
	DistributionProperty owl.ObjectProperty = "http://www.w3.org/ns/dcat#distribution"

	// DownloadURL is dcat:downloadURL, "URL de descarga".
	//
	// Ceci est un lien direct à un fichier téléchargeable en un format
	// donnée. Exple fichier CSV ou RDF. Le format est décrit par les
	// propriétés de distribution dcterms:format et/ou dcat:mediaType.
	DownloadURL owl.ObjectProperty = "http://www.w3.org/ns/dcat#downloadURL"

	// EndpointDescription is dcat:endpointDescription, "descripción del
	// end-point del servicio".
	//
	// A description of the service end-point, including its operations,
	// parameters etc.
	EndpointDescription owl.ObjectProperty = "http://www.w3.org/ns/dcat#endpointDescription"

	// EndpointURL is dcat:endpointURL, "end-point del servicio".
	//
	// Kořenové umístění nebo hlavní přístupový bod služby (IRI
	// přístupné přes Web).
	EndpointURL owl.ObjectProperty = "http://www.w3.org/ns/dcat#endpointURL"

	// First is dcat:first.
	//
	// El primer recurso en una colección ordenada o serie de recursos, al que
	// el recurso pertenece.
	First owl.ObjectProperty = "http://www.w3.org/ns/dcat#first"

	// HadRole is dcat:hadRole, "haRuolo".
	//
	// Den funktion en entitet eller aktør har i forhold til en anden
	// ressource.
	HadRole owl.ObjectProperty = "http://www.w3.org/ns/dcat#hadRole"

	// HasCurrentVersion is dcat:hasCurrentVersion, "ha versione attuale".
	//
	// Este recurso es más específico y versionado con contenido equivalente
	// [PAV].
	HasCurrentVersion owl.ObjectProperty = "http://www.w3.org/ns/dcat#hasCurrentVersion"

	// HasVersion is dcat:hasVersion, "ha versione".
	//
	// Este recurso tiene una versión específica.
	HasVersion owl.ObjectProperty = "http://www.w3.org/ns/dcat#hasVersion"

	// InCatalog is dcat:inCatalog.
	InCatalog owl.ObjectProperty = "http://www.w3.org/ns/dcat#inCatalog"

	// InSeries is dcat:inSeries, "en serie".
	//
	// A dataset series of which the dataset is part.
	InSeries owl.ObjectProperty = "http://www.w3.org/ns/dcat#inSeries"

	// IsDistributionOf is dcat:isDistributionOf.
	IsDistributionOf owl.ObjectProperty = "http://www.w3.org/ns/dcat#isDistributionOf"

	// IsVersionOf is dcat:isVersionOf.
	IsVersionOf owl.ObjectProperty = "http://www.w3.org/ns/dcat#isVersionOf"

	// LandingPage is dcat:landingPage, "destinationsside".
	//
	// A Web page that can be navigated to in a Web browser to gain access to
	// the catalog, a dataset, its distributions and/or additional information.
	LandingPage owl.ObjectProperty = "http://www.w3.org/ns/dcat#landingPage"

	// Last is dcat:last.
	//
	// El último recurso en una colección ordenada o serie de recursos, al
	// que el recurso pertenece.
	Last owl.ObjectProperty = "http://www.w3.org/ns/dcat#last"

	// MediaType is dcat:mediaType, "media type".
	//
	// Cette propriété doit être utilisée quand c'est définit le type de
	// média de la distribution en IANA, sinon dcterms:format DOIT être
	// utilisé avec différentes valeurs.
	MediaType owl.ObjectProperty = "http://www.w3.org/ns/dcat#mediaType"

	// Next is dcat:next.
	Next owl.ObjectProperty = "http://www.w3.org/ns/dcat#next"

	// NextVersion is dcat:nextVersion.
	NextVersion owl.ObjectProperty = "http://www.w3.org/ns/dcat#nextVersion"

	// PackageFormat is dcat:packageFormat, "formato de empaquetado".
	//
	// Balíčkový formát souboru, ve kterém je jeden či více souborů
	// seskupeno dohromady, např. aby bylo možné stáhnout sadu
	// souvisejících souborů naráz.
	PackageFormat owl.ObjectProperty = "http://www.w3.org/ns/dcat#packageFormat"

	// Prev is dcat:prev, "precedente".
	//
	// La risorsa precedente a quella attuale in una collezione ordinata o in
	// una serie di risorse.
	Prev owl.ObjectProperty = "http://www.w3.org/ns/dcat#prev"

	// PreviousVersion is dcat:previousVersion, "previous version".
	//
	// La versione precedente di una risorsa.
	PreviousVersion owl.ObjectProperty = "http://www.w3.org/ns/dcat#previousVersion"

	// QualifiedRelation is dcat:qualifiedRelation, "Kvalificeret relation".
	//
	// Enlace a una descripción de la relación con otro recurso.
	QualifiedRelation owl.ObjectProperty = "http://www.w3.org/ns/dcat#qualifiedRelation"

	// Record is dcat:record, "post".
	//
	// A record describing the registration of a single dataset or data service
	// that is part of the catalog.
	Record owl.ObjectProperty = "http://www.w3.org/ns/dcat#record"

	// ResourceProperty is dcat:resource.
	//
	// A resource that is listed in the catalog.
	ResourceProperty owl.ObjectProperty = "http://www.w3.org/ns/dcat#resource"

	// SeriesMember is dcat:seriesMember.
	SeriesMember owl.ObjectProperty = "http://www.w3.org/ns/dcat#seriesMember"

	// ServesDataset is dcat:servesDataset, "datatjeneste for datasæt".
	//
	// A collection of data that this DataService can distribute.
	ServesDataset owl.ObjectProperty = "http://www.w3.org/ns/dcat#servesDataset"

	// Service is dcat:service, "datatjeneste".
	//
	// A service that is listed in the catalog.
	Service owl.ObjectProperty = "http://www.w3.org/ns/dcat#service"

	// Theme is dcat:theme, "emne".
	//
	// A main category of the resource. A resource can have multiple themes.
	Theme owl.ObjectProperty = "http://www.w3.org/ns/dcat#theme"

	// ThemeTaxonomy is dcat:themeTaxonomy, "emnetaksonomi".
	//
	// El sistema de organización del conocimiento utilizado para clasificar
	// conjuntos de datos de catálogos.
	ThemeTaxonomy owl.ObjectProperty = "http://www.w3.org/ns/dcat#themeTaxonomy"
)

// Data properties.
const (
	// Bbox is dcat:bbox, "bounding box".
	//
	// Den geografiske omskrevne firkant af en ressource.
	Bbox owl.DataProperty = "http://www.w3.org/ns/dcat#bbox"

	// ByteSize is dcat:byteSize, "byte size".
	//
	// El tamaño de una distribución en bytes.
	ByteSize owl.DataProperty = "http://www.w3.org/ns/dcat#byteSize"

	// Centroid is dcat:centroid.
	//
	// Det geometrisk tyngdepunkt (centroid) for en ressource.
	Centroid owl.DataProperty = "http://www.w3.org/ns/dcat#centroid"

	// EndDate is dcat:endDate, "data di fine".
	//
	// El fin del período.
	EndDate owl.DataProperty = "http://www.w3.org/ns/dcat#endDate"

	// Keyword is dcat:keyword.
	//
	// A keyword or tag describing a resource.
	Keyword owl.DataProperty = "http://www.w3.org/ns/dcat#keyword"

	// SpatialResolutionInMeters is dcat:spatialResolutionInMeters, "geografisk
	// opløsning (meter)".
	//
	// mindste geografiske afstand som kan erkendes i et datasæt, målt i
	// meter.
	SpatialResolutionInMeters owl.DataProperty = "http://www.w3.org/ns/dcat#spatialResolutionInMeters"

	// StartDate is dcat:startDate, "data di inizio".
	//
	// El comienzo del período
	StartDate owl.DataProperty = "http://www.w3.org/ns/dcat#startDate"

	// TemporalResolution is dcat:temporalResolution, "resolución temporal".
	//
	// mindste tidsperiode der kan resolveres i datasættet.
	TemporalResolution owl.DataProperty = "http://www.w3.org/ns/dcat#temporalResolution"

	// Version is dcat:version.
	//
	// El indicador de versión (nombre o identificador) del recurso.
	Version owl.DataProperty = "http://www.w3.org/ns/dcat#version"
)

// Annotation properties.
const (
	// HasCurrentVersionAnnotation is dcat:hasCurrentVersion, "ha versione
	// attuale".
	//
	// Este recurso es más específico y versionado con contenido equivalente
	// [PAV].
	HasCurrentVersionAnnotation owl.AnnotationProperty = "http://www.w3.org/ns/dcat#hasCurrentVersion"

	// HasVersionAnnotation is dcat:hasVersion, "ha versione".
	//
	// Este recurso tiene una versión específica.
	HasVersionAnnotation owl.AnnotationProperty = "http://www.w3.org/ns/dcat#hasVersion"

	// PreviousVersionAnnotation is dcat:previousVersion, "previous version".
	//
	// La versione precedente di una risorsa.
	PreviousVersionAnnotation owl.AnnotationProperty = "http://www.w3.org/ns/dcat#previousVersion"

	// VersionAnnotation is dcat:version.
	//
	// El indicador de versión (nombre o identificador) del recurso.
	VersionAnnotation owl.AnnotationProperty = "http://www.w3.org/ns/dcat#version"
)

//go:embed dcat.ofn
var source string

// Ontology returns the vocabulary's axioms: its declarations, its class and
// property hierarchy, and the labels and definitions its authors wrote.
//
// Each call parses a fresh ontology, so the result is the caller's to add to
// or rewrite. Use [Vocabulary] instead to look terms up without copying.
func Ontology() *owl.Ontology {
	o, err := owl.ParseFunctionalString(source)
	if err != nil {
		panic("dcat: generated ontology does not parse: " + err.Error())
	}
	return o
}

// Vocabulary returns the terms with their labels and definitions, as the
// closed set an untrusted axiom can be validated against. It is built once and
// is safe to share.
func Vocabulary() *owl.Vocabulary { return vocabulary() }

var vocabulary = sync.OnceValue(func() *owl.Vocabulary {
	return owl.NewVocabulary(Ontology())
})
